// AUTO-DERIVED from SSMxT 2022 calculation linkbases — regenerate with
// scripts/gen-mbrs-template.py --taxonomy. [role, parent, child, weight]

export const MBRS_CALC: [string, string, string, number][] = [
  ["200100", "ifrs-smes:CurrentAssets", "ifrs-smes:CurrentTaxAssetsCurrent", 1],
  ["200100", "ifrs-smes:CurrentAssets", "ifrs-smes:InventoriesTotal", 1],
  ["200100", "ifrs-smes:CurrentAssets", "ifrs-smes:TradeAndOtherCurrentReceivables", 1],
  ["200100", "ifrs-smes:CurrentAssets", "ssmt-mpers:CurrentBiologicalAssets", 1],
  ["200100", "ifrs-smes:CurrentAssets", "ssmt-mpers:CurrentDerivativeFinancialAssets", 1],
  ["200100", "ifrs-smes:CurrentAssets", "ssmt-mpers:CurrentInvestments", 1],
  ["200100", "ifrs-smes:CurrentAssets", "ssmt-mpers:OtherCurrentAssets", 1],
  ["200100", "ifrs-smes:CurrentAssets", "ssmt:CashAndBankBalances", 1],
  ["200100", "ifrs-smes:CurrentLiabilities", "ifrs-smes:CurrentProvisions", 1],
  ["200100", "ifrs-smes:CurrentLiabilities", "ifrs-smes:CurrentProvisionsForEmployeeBenefits", 1],
  ["200100", "ifrs-smes:CurrentLiabilities", "ifrs-smes:CurrentTaxLiabilitiesCurrent", 1],
  ["200100", "ifrs-smes:CurrentLiabilities", "ifrs-smes:DeferredIncomeClassifiedAsCurrent", 1],
  ["200100", "ifrs-smes:CurrentLiabilities", "ifrs-smes:ShorttermBorrowings", 1],
  ["200100", "ifrs-smes:CurrentLiabilities", "ifrs-smes:TradeAndOtherCurrentPayables", 1],
  ["200100", "ifrs-smes:CurrentLiabilities", "ssmt-mpers:CurrentDerivativeFinancialLiabilities", 1],
  ["200100", "ifrs-smes:CurrentLiabilities", "ssmt-mpers:OtherCurrentLiabilities", 1],
  ["200100", "ifrs-smes:EquityAttributableToOwnersOfParent", "ifrs-smes:IssuedCapital", 1],
  ["200100", "ifrs-smes:EquityAttributableToOwnersOfParent", "ifrs-smes:OtherReserves", 1],
  ["200100", "ifrs-smes:EquityAttributableToOwnersOfParent", "ifrs-smes:RetainedEarnings", 1],
  ["200100", "ifrs-smes:EquityAttributableToOwnersOfParent", "ifrs-smes:TreasuryShares", -1],
  ["200100", "ifrs-smes:NoncurrentAssets", "ifrs-smes:DeferredTaxAssets", 1],
  ["200100", "ifrs-smes:NoncurrentAssets", "ifrs-smes:IntangibleAssetsAndGoodwill", 1],
  ["200100", "ifrs-smes:NoncurrentAssets", "ifrs-smes:InvestmentProperty", 1],
  ["200100", "ifrs-smes:NoncurrentAssets", "ifrs-smes:InvestmentsInAssociates", 1],
  ["200100", "ifrs-smes:NoncurrentAssets", "ifrs-smes:InvestmentsInJointVentures", 1],
  ["200100", "ifrs-smes:NoncurrentAssets", "ifrs-smes:NoncurrentReceivables", 1],
  ["200100", "ifrs-smes:NoncurrentAssets", "ifrs-smes:PropertyPlantAndEquipment", 1],
  ["200100", "ifrs-smes:NoncurrentAssets", "ssmt-mpers:InvestmentInSubisidiaries", 1],
  ["200100", "ifrs-smes:NoncurrentAssets", "ssmt-mpers:NoncurrentBiologicalAssets", 1],
  ["200100", "ifrs-smes:NoncurrentAssets", "ssmt-mpers:NoncurrentInvestmentsOtherThanInvestmentsAccountedForUsingEquityMethod", 1],
  ["200100", "ifrs-smes:NoncurrentAssets", "ssmt-mpers:OtherNoncurrentAssets", 1],
  ["200100", "ifrs-smes:NoncurrentLiabilities", "ifrs-smes:DeferredIncomeClassifiedAsNoncurrent", 1],
  ["200100", "ifrs-smes:NoncurrentLiabilities", "ifrs-smes:DeferredTaxLiabilities", 1],
  ["200100", "ifrs-smes:NoncurrentLiabilities", "ifrs-smes:NoncurrentPayables", 1],
  ["200100", "ifrs-smes:NoncurrentLiabilities", "ifrs-smes:NoncurrentProvisions", 1],
  ["200100", "ifrs-smes:NoncurrentLiabilities", "ifrs-smes:NoncurrentProvisionsForEmployeeBenefits", 1],
  ["200100", "ifrs-smes:NoncurrentLiabilities", "ssmt-mpers:NoncurrentBorrowings", 1],
  ["200100", "ifrs-smes:NoncurrentLiabilities", "ssmt-mpers:OtherNoncurrentLiabilities", 1],
  ["200200", "ifrs-smes:Borrowings", "ssmt-mpers:CurrentPortionOfNoncurrentUnsecuredOtherBankLoansReceived", 1],
  ["200200", "ifrs-smes:Borrowings", "ssmt-mpers:OtherBorrowings", 1],
  ["200200", "ifrs-smes:Borrowings", "ssmt-mpers:OtherBorrowingsFinanceLeaseLiabilities", 1],
  ["200200", "ifrs-smes:Borrowings", "ssmt-mpers:OtherBorrowingsLoanFromAssociates", 1],
  ["200200", "ifrs-smes:Borrowings", "ssmt-mpers:OtherBorrowingsLoanFromHoldingCompany", 1],
  ["200200", "ifrs-smes:Borrowings", "ssmt-mpers:OtherBorrowingsLoanFromJointVentures", 1],
  ["200200", "ifrs-smes:Borrowings", "ssmt-mpers:OtherBorrowingsLoanFromOtherRelatedCompanies", 1],
  ["200200", "ifrs-smes:Borrowings", "ssmt-mpers:OtherBorrowingsLoanFromSubsidiaries", 1],
  ["200200", "ifrs-smes:Borrowings", "ssmt-mpers:OtherBorrowingsRedeemablePreferenceShares", 1],
  ["200200", "ifrs-smes:Borrowings", "ssmt-mpers:OtherSecuredBankLoansReceived", 1],
  ["200200", "ifrs-smes:Borrowings", "ssmt-mpers:SecuredBankLoansReceived", 1],
  ["200200", "ifrs-smes:Borrowings", "ssmt-mpers:SecuredBankOverdrafts", 1],
  ["200200", "ifrs-smes:Borrowings", "ssmt-mpers:SecuredConvertibleNotes", 1],
  ["200200", "ifrs-smes:Borrowings", "ssmt-mpers:UnsecuredBankLoansReceived", 1],
  ["200200", "ifrs-smes:Borrowings", "ssmt-mpers:UnsecuredBankOverdrafts", 1],
  ["200200", "ifrs-smes:Borrowings", "ssmt-mpers:UnsecuredConvertibleNotes", 1],
  ["200200", "ifrs-smes:Buildings", "ssmt-mpers:BuildingOnFreeholdLand", 1],
  ["200200", "ifrs-smes:Buildings", "ssmt-mpers:BuildingOnLongtermLeaseholdLand", 1],
  ["200200", "ifrs-smes:Buildings", "ssmt-mpers:BuildingOnShorttermLeaseholdLand", 1],
  ["200200", "ifrs-smes:Buildings", "ssmt-mpers:LeasedProperties", 1],
  ["200200", "ifrs-smes:Cash", "ifrs-smes:BalancesWithBanks", 1],
  ["200200", "ifrs-smes:Cash", "ifrs-smes:CashOnHand", 1],
  ["200200", "ifrs-smes:CashEquivalents", "ifrs-smes:BankingArrangementsClassifiedAsCashEquivalents", 1],
  ["200200", "ifrs-smes:CashEquivalents", "ifrs-smes:ShorttermDepositsClassifiedAsCashEquivalents", 1],
  ["200200", "ifrs-smes:CashEquivalents", "ifrs-smes:ShorttermInvestmentsClassifiedAsCashEquivalents", 1],
  ["200200", "ifrs-smes:CashEquivalents", "ssmt-mpers:CashEquivalentsWithOtherFinancialInstitutions", 1],
  ["200200", "ifrs-smes:CashEquivalents", "ssmt-mpers:DepositsAndPlacementsWithLicensedBanks", 1],
  ["200200", "ifrs-smes:CashEquivalents", "ssmt-mpers:DepositsPlacedWithOtherCorporations", 1],
  ["200200", "ifrs-smes:CashEquivalents", "ssmt-mpers:FixedDepositsWithFinancialInstitutions", 1],
  ["200200", "ifrs-smes:CurrentProvisions", "ifrs-smes:OtherShorttermProvisions", 1],
  ["200200", "ifrs-smes:CurrentProvisions", "ifrs-smes:ShorttermLegalProceedingsProvision", 1],
  ["200200", "ifrs-smes:CurrentProvisions", "ifrs-smes:ShorttermOnerousContractsProvision", 1],
  ["200200", "ifrs-smes:CurrentProvisions", "ifrs-smes:ShorttermRestructuringProvision", 1],
  ["200200", "ifrs-smes:CurrentProvisions", "ifrs-smes:ShorttermWarrantyProvision", 1],
  ["200200", "ifrs-smes:CurrentProvisions", "ssmt-mpers:ShorttermProvisionForDecommissioningRestorationAndRehabilitationCosts", 1],
  ["200200", "ifrs-smes:CurrentProvisionsForEmployeeBenefits", "ssmt-mpers:CurrentCashSettledShareBasedPaymentLiability", 1],
  ["200200", "ifrs-smes:CurrentProvisionsForEmployeeBenefits", "ssmt-mpers:CurrentDefinedBenefitPlan", 1],
  ["200200", "ifrs-smes:CurrentProvisionsForEmployeeBenefits", "ssmt-mpers:CurrentDefinedContributionPlan", 1],
  ["200200", "ifrs-smes:CurrentProvisionsForEmployeeBenefits", "ssmt-mpers:CurrentEmploymentTerminationBenefits", 1],
  ["200200", "ifrs-smes:CurrentProvisionsForEmployeeBenefits", "ssmt-mpers:CurrentOtherEmployeeBenefitLiabilities", 1],
  ["200200", "ifrs-smes:CurrentProvisionsForEmployeeBenefits", "ssmt-mpers:CurrentProvisionForUnconsumedLeave", 1],
  ["200200", "ifrs-smes:IntangibleAssetsAndGoodwill", "ifrs-smes:Goodwill", 1],
  ["200200", "ifrs-smes:IntangibleAssetsAndGoodwill", "ifrs-smes:IntangibleAssetsOtherThanGoodwill", 1],
  ["200200", "ifrs-smes:IntangibleAssetsOtherThanGoodwill", "ifrs-smes:CopyrightsPatentsAndOtherIndustrialPropertyRightsServiceAndOperatingRights", 1],
  ["200200", "ifrs-smes:IntangibleAssetsOtherThanGoodwill", "ifrs-smes:OtherIntangibleAssets", 1],
  ["200200", "ifrs-smes:InventoriesTotal", "ifrs-smes:WorkInProgress", 1],
  ["200200", "ifrs-smes:InventoriesTotal", "ssmt-mpers:FinishedGoods", 1],
  ["200200", "ifrs-smes:InventoriesTotal", "ssmt-mpers:OtherInventories", 1],
  ["200200", "ifrs-smes:InventoriesTotal", "ssmt-mpers:RawMaterials", 1],
  ["200200", "ifrs-smes:InventoriesTotal", "ssmt-mpers:SpareParts", 1],
  ["200200", "ifrs-smes:InvestmentProperty", "ssmt-mpers:InvestmentPropertyBuildingUnderConstruction", 1],
  ["200200", "ifrs-smes:InvestmentProperty", "ssmt-mpers:InvestmentPropertyFreeholdLandAndBuilding", 1],
  ["200200", "ifrs-smes:InvestmentProperty", "ssmt-mpers:InvestmentPropertyLongtermLeaseholdLand", 1],
  ["200200", "ifrs-smes:InvestmentProperty", "ssmt-mpers:InvestmentPropertyShorttermLeaseholdLand", 1],
  ["200200", "ifrs-smes:InvestmentProperty", "ssmt-mpers:OtherInvestmentProperty", 1],
  ["200200", "ifrs-smes:InvestmentsInAssociates", "ssmt-mpers:InvestmentInAssociatesQuotedSharesInMalaysia", 1],
  ["200200", "ifrs-smes:InvestmentsInAssociates", "ssmt-mpers:InvestmentInAssociatesQuotedSharesOutsideMalaysia", 1],
  ["200200", "ifrs-smes:InvestmentsInAssociates", "ssmt-mpers:InvestmentsInAssociatesOtherInvestmentsNetOfImpairmentLosses", 1],
  ["200200", "ifrs-smes:InvestmentsInAssociates", "ssmt-mpers:InvestmentsInAssociatesShareOfPostAcquisitionProfitsAndReserves", 1],
  ["200200", "ifrs-smes:InvestmentsInAssociates", "ssmt-mpers:InvestmentsInAssociatesUnquotedSharesNetOfImpairmentLosses", 1],
  ["200200", "ifrs-smes:InvestmentsInJointVentures", "ssmt-mpers:InvestmentInJointVenturesQuotedSharesInMalaysia", 1],
  ["200200", "ifrs-smes:InvestmentsInJointVentures", "ssmt-mpers:InvestmentInJointVenturesQuotedSharesOutsideMalaysia", 1],
  ["200200", "ifrs-smes:InvestmentsInJointVentures", "ssmt-mpers:InvestmentsInJointVentureOtherInvestment", 1],
  ["200200", "ifrs-smes:InvestmentsInJointVentures", "ssmt-mpers:InvestmentsInJointVentureShareOfPostAcquisitionProfitsAndReserves", 1],
  ["200200", "ifrs-smes:InvestmentsInJointVentures", "ssmt-mpers:InvestmentsInJointVentureUnquotedSharesNetOfImpairmentLosses", 1],
  ["200200", "ifrs-smes:IssuedCapital", "ssmt-mpers:CapitalFromNonredeemablePreferenceShares", 1],
  ["200200", "ifrs-smes:IssuedCapital", "ssmt-mpers:CapitalFromOrdinaryShares", 1],
  ["200200", "ifrs-smes:IssuedCapital", "ssmt-mpers:CapitalFromRedeemablePreferenceShares", 1],
  ["200200", "ifrs-smes:Land", "ssmt-mpers:FreeholdLand", 1],
  ["200200", "ifrs-smes:Land", "ssmt-mpers:LongtermLeaseholdLand", 1],
  ["200200", "ifrs-smes:Land", "ssmt-mpers:ShorttermLeaseholdLand", 1],
  ["200200", "ifrs-smes:LandAndBuildings", "ifrs-smes:Buildings", 1],
  ["200200", "ifrs-smes:LandAndBuildings", "ifrs-smes:Land", 1],
  ["200200", "ifrs-smes:NoncurrentPayables", "ifrs-smes:NoncurrentPayablesToTradeSuppliers", 1],
  ["200200", "ifrs-smes:NoncurrentPayables", "ssmt-mpers:OtherNoncurrentPayables", 1],
  ["200200", "ifrs-smes:NoncurrentPayablesToTradeSuppliers", "ssmt-mpers:NoncurrentTradePayablesDueToAssociates", 1],
  ["200200", "ifrs-smes:NoncurrentPayablesToTradeSuppliers", "ssmt-mpers:NoncurrentTradePayablesDueToHoldingCompany", 1],
  ["200200", "ifrs-smes:NoncurrentPayablesToTradeSuppliers", "ssmt-mpers:NoncurrentTradePayablesDueToJointVentures", 1],
  ["200200", "ifrs-smes:NoncurrentPayablesToTradeSuppliers", "ssmt-mpers:NoncurrentTradePayablesDueToOtherRelatedParties", 1],
  ["200200", "ifrs-smes:NoncurrentPayablesToTradeSuppliers", "ssmt-mpers:NoncurrentTradePayablesDueToSubsidiaries", 1],
  ["200200", "ifrs-smes:NoncurrentPayablesToTradeSuppliers", "ssmt-mpers:OtherNoncurrentTradePayables", 1],
  ["200200", "ifrs-smes:NoncurrentProvisions", "ifrs-smes:LongtermLegalProceedingsProvision", 1],
  ["200200", "ifrs-smes:NoncurrentProvisions", "ifrs-smes:LongtermMiscellaneousOtherProvisions", 1],
  ["200200", "ifrs-smes:NoncurrentProvisions", "ifrs-smes:LongtermOnerousContractsProvision", 1],
  ["200200", "ifrs-smes:NoncurrentProvisions", "ifrs-smes:LongtermRestructuringProvision", 1],
  ["200200", "ifrs-smes:NoncurrentProvisions", "ifrs-smes:LongtermWarrantyProvision", 1],
  ["200200", "ifrs-smes:NoncurrentProvisions", "ssmt-mpers:LongtermProvisionForDecommissioningRestorationAndRehabilitationCosts", 1],
  ["200200", "ifrs-smes:NoncurrentProvisionsForEmployeeBenefits", "ssmt-mpers:CashSettledShareBasedPaymentLiability", 1],
  ["200200", "ifrs-smes:NoncurrentProvisionsForEmployeeBenefits", "ssmt-mpers:DefinedBenefitPlan", 1],
  ["200200", "ifrs-smes:NoncurrentProvisionsForEmployeeBenefits", "ssmt-mpers:DefinedContributionPlan", 1],
  ["200200", "ifrs-smes:NoncurrentProvisionsForEmployeeBenefits", "ssmt-mpers:EmploymentTerminationBenefits", 1],
  ["200200", "ifrs-smes:NoncurrentProvisionsForEmployeeBenefits", "ssmt-mpers:OtherEmployeeBenefitLiabilities", 1],
  ["200200", "ifrs-smes:NoncurrentProvisionsForEmployeeBenefits", "ssmt-mpers:ProvisionForUnconsumedLeave", 1],
  ["200200", "ifrs-smes:NoncurrentReceivables", "ssmt-mpers:NoncurrentTradeReceivables", 1],
  ["200200", "ifrs-smes:NoncurrentReceivables", "ssmt-mpers:OtherNoncurrentReceivables", 1],
  ["200200", "ifrs-smes:NoncurrentReceivables", "ssmt-mpers:OtherNoncurrentReceivablesDueFromRelatedParties", 1],
  ["200200", "ifrs-smes:OtherReserves", "ssmt-mpers:DistributableReseves", 1],
  ["200200", "ifrs-smes:OtherReserves", "ssmt-mpers:NondistributableReserves", 1],
  ["200200", "ifrs-smes:PropertyPlantAndEquipment", "ifrs-smes:ConstructionInProgress", 1],
  ["200200", "ifrs-smes:PropertyPlantAndEquipment", "ifrs-smes:LandAndBuildings", 1],
  ["200200", "ifrs-smes:PropertyPlantAndEquipment", "ifrs-smes:Machinery", 1],
  ["200200", "ifrs-smes:PropertyPlantAndEquipment", "ifrs-smes:OtherPropertyPlantAndEquipment", 1],
  ["200200", "ifrs-smes:PropertyPlantAndEquipment", "ifrs-smes:Vehicles", 1],
  ["200200", "ifrs-smes:PropertyPlantAndEquipment", "ssmt-mpers:OfficeEquipmentFixtureAndFittings", 1],
  ["200200", "ifrs-smes:PropertyPlantAndEquipment", "ssmt-mpers:PlantAndEquipment", 1],
  ["200200", "ifrs-smes:Provisions", "ifrs-smes:LegalProceedingsProvision", 1],
  ["200200", "ifrs-smes:Provisions", "ifrs-smes:OnerousContractsProvision", 1],
  ["200200", "ifrs-smes:Provisions", "ifrs-smes:OtherProvisions", 1],
  ["200200", "ifrs-smes:Provisions", "ifrs-smes:RestructuringProvision", 1],
  ["200200", "ifrs-smes:Provisions", "ifrs-smes:WarrantyProvision", 1],
  ["200200", "ifrs-smes:Provisions", "ssmt-mpers:ProvisionForDecommissioningRestorationAndRehabilitationCosts", 1],
  ["200200", "ifrs-smes:ProvisionsForEmployeeBenefits", "ssmt-mpers:CashSettledShareBasedPaymentLiability", 1],
  ["200200", "ifrs-smes:ProvisionsForEmployeeBenefits", "ssmt-mpers:DefinedBenefitPlan", 1],
  ["200200", "ifrs-smes:ProvisionsForEmployeeBenefits", "ssmt-mpers:DefinedContributionPlan", 1],
  ["200200", "ifrs-smes:ProvisionsForEmployeeBenefits", "ssmt-mpers:EmploymentTerminationBenefits", 1],
  ["200200", "ifrs-smes:ProvisionsForEmployeeBenefits", "ssmt-mpers:OtherEmployeeBenefitLiabilities", 1],
  ["200200", "ifrs-smes:ProvisionsForEmployeeBenefits", "ssmt-mpers:ProvisionForUnconsumedLeave", 1],
  ["200200", "ifrs-smes:ShorttermBorrowings", "ssmt-mpers:CurrenPortionOfSecuredConvertibleNotes", 1],
  ["200200", "ifrs-smes:ShorttermBorrowings", "ssmt-mpers:CurrentPortionOfFinanceLeaseLiabilities", 1],
  ["200200", "ifrs-smes:ShorttermBorrowings", "ssmt-mpers:CurrentPortionOfLoanFromHoldingCompany", 1],
  ["200200", "ifrs-smes:ShorttermBorrowings", "ssmt-mpers:CurrentPortionOfLoanFromOtherRelatedCompanies", 1],
  ["200200", "ifrs-smes:ShorttermBorrowings", "ssmt-mpers:CurrentPortionOfNoncurrentSecuredBankOverdrafts", 1],
  ["200200", "ifrs-smes:ShorttermBorrowings", "ssmt-mpers:CurrentPortionOfNoncurrentSecuredOtherBankLoanReceived", 1],
  ["200200", "ifrs-smes:ShorttermBorrowings", "ssmt-mpers:CurrentPortionOfNoncurrentUnsecuredBankOverdrafts", 1],
  ["200200", "ifrs-smes:ShorttermBorrowings", "ssmt-mpers:CurrentPortionOfNoncurrentUnsecuredOtherBankLoansReceived", 1],
  ["200200", "ifrs-smes:ShorttermBorrowings", "ssmt-mpers:CurrentPortionOfUnsecuredConvertibleNotes", 1],
  ["200200", "ifrs-smes:ShorttermBorrowings", "ssmt-mpers:CurrentSecuredBankLoansReceivedAndCurrentPortionOfNoncurrentSecuredBankLoansReceived", 1],
  ["200200", "ifrs-smes:ShorttermBorrowings", "ssmt-mpers:CurrentUnsecuredBankLoansReceivedAndCurrentPortionOfNoncurrentUnsecuredBankLoansReceived", 1],
  ["200200", "ifrs-smes:ShorttermBorrowings", "ssmt-mpers:OtherCurrentPortionOfLoanFromAssociates", 1],
  ["200200", "ifrs-smes:ShorttermBorrowings", "ssmt-mpers:OtherCurrentPortionOfLoanFromJointVentures", 1],
  ["200200", "ifrs-smes:ShorttermBorrowings", "ssmt-mpers:OtherCurrentPortionOfLoanFromSubsidiaries", 1],
  ["200200", "ifrs-smes:ShorttermBorrowings", "ssmt-mpers:OtherCurrentPortionOfMiscellaneousBorrowings", 1],
  ["200200", "ifrs-smes:ShorttermBorrowings", "ssmt-mpers:OtherCurrentPortionOfRedeemablePreferenceShares", 1],
  ["200200", "ifrs-smes:TradeAndOtherCurrentPayables", "ifrs-smes:TradeAndOtherCurrentPayablesToTradeSuppliers", 1],
  ["200200", "ifrs-smes:TradeAndOtherCurrentPayables", "ssmt-mpers:OtherCurrentPayables", 1],
  ["200200", "ifrs-smes:TradeAndOtherCurrentPayablesToTradeSuppliers", "ssmt-mpers:CurrentTradePayableDueToContractCustomer", 1],
  ["200200", "ifrs-smes:TradeAndOtherCurrentPayablesToTradeSuppliers", "ssmt-mpers:CurrentTradePayablesDueToAssociates", 1],
  ["200200", "ifrs-smes:TradeAndOtherCurrentPayablesToTradeSuppliers", "ssmt-mpers:CurrentTradePayablesDueToHoldingCompany", 1],
  ["200200", "ifrs-smes:TradeAndOtherCurrentPayablesToTradeSuppliers", "ssmt-mpers:CurrentTradePayablesDueToJointVentures", 1],
  ["200200", "ifrs-smes:TradeAndOtherCurrentPayablesToTradeSuppliers", "ssmt-mpers:CurrentTradePayablesDueToRelatedCompanies", 1],
  ["200200", "ifrs-smes:TradeAndOtherCurrentPayablesToTradeSuppliers", "ssmt-mpers:CurrentTradePayablesDueToSubsidiaries", 1],
  ["200200", "ifrs-smes:TradeAndOtherCurrentPayablesToTradeSuppliers", "ssmt-mpers:OtherCurrentTradePayables", 1],
  ["200200", "ifrs-smes:TradeAndOtherCurrentReceivables", "ssmt-mpers:CurrentTradeReceivables", 1],
  ["200200", "ifrs-smes:TradeAndOtherCurrentReceivables", "ssmt-mpers:OtherCurrentReceivables", 1],
  ["200200", "ifrs-smes:TradeAndOtherPayables", "ifrs-smes:TradeAndOtherPayablesToTradeSuppliers", 1],
  ["200200", "ifrs-smes:TradeAndOtherPayables", "ssmt-mpers:OtherPayables", 1],
  ["200200", "ifrs-smes:TradeAndOtherPayablesToTradeSuppliers", "ssmt-mpers:OtherTradePayables", 1],
  ["200200", "ifrs-smes:TradeAndOtherPayablesToTradeSuppliers", "ssmt-mpers:TradePayablesDueToAssociates", 1],
  ["200200", "ifrs-smes:TradeAndOtherPayablesToTradeSuppliers", "ssmt-mpers:TradePayablesDueToContractCustomers", 1],
  ["200200", "ifrs-smes:TradeAndOtherPayablesToTradeSuppliers", "ssmt-mpers:TradePayablesDueToHoldingCompany", 1],
  ["200200", "ifrs-smes:TradeAndOtherPayablesToTradeSuppliers", "ssmt-mpers:TradePayablesDueToJointVentures", 1],
  ["200200", "ifrs-smes:TradeAndOtherPayablesToTradeSuppliers", "ssmt-mpers:TradePayablesDueToOtherRelatedParties", 1],
  ["200200", "ifrs-smes:TradeAndOtherPayablesToTradeSuppliers", "ssmt-mpers:TradePayablesDueToSubsidiaries", 1],
  ["200200", "ifrs-smes:TradeAndOtherReceivables", "ssmt-mpers:OtherReceivables", 1],
  ["200200", "ifrs-smes:TradeAndOtherReceivables", "ssmt-mpers:TradeReceivables", 1],
  ["200200", "ssmt-mpers:CurrentNontradePayables", "ssmt-mpers:CurrentNontradeAccruals", 1],
  ["200200", "ssmt-mpers:CurrentNontradePayables", "ssmt-mpers:CurrentNontradeDeferredIncome", 1],
  ["200200", "ssmt-mpers:CurrentNontradePayables", "ssmt-mpers:CurrentNontradeRetentionPayable", 1],
  ["200200", "ssmt-mpers:CurrentNontradePayables", "ssmt-mpers:OtherCurrentNontradePayables", 1],
  ["200200", "ssmt-mpers:CurrentTradeReceivables", "ssmt-mpers:CurrentTradeReceivablesDueFromAssociates", 1],
  ["200200", "ssmt-mpers:CurrentTradeReceivables", "ssmt-mpers:CurrentTradeReceivablesDueFromContractCustomers", 1],
  ["200200", "ssmt-mpers:CurrentTradeReceivables", "ssmt-mpers:CurrentTradeReceivablesDueFromHoldingCompany", 1],
  ["200200", "ssmt-mpers:CurrentTradeReceivables", "ssmt-mpers:CurrentTradeReceivablesDueFromJointVentures", 1],
  ["200200", "ssmt-mpers:CurrentTradeReceivables", "ssmt-mpers:CurrentTradeReceivablesDueFromRelatedParties", 1],
  ["200200", "ssmt-mpers:CurrentTradeReceivables", "ssmt-mpers:CurrentTradeReceivablesDueFromSubsidiaries", 1],
  ["200200", "ssmt-mpers:CurrentTradeReceivables", "ssmt-mpers:OtherCurrentTradeReceivables", 1],
  ["200200", "ssmt-mpers:DistributableReseves", "ssmt-mpers:OtherDistributableReserve", 1],
  ["200200", "ssmt-mpers:InvestmentInSubisidiaries", "ssmt-mpers:InvestmentInSubsidiariesQuotedSharesInMalaysia", 1],
  ["200200", "ssmt-mpers:InvestmentInSubisidiaries", "ssmt-mpers:InvestmentInSubsidiariesQuotedSharesOutsideMalaysia", 1],
  ["200200", "ssmt-mpers:InvestmentInSubisidiaries", "ssmt-mpers:InvestmentsInSubsidiariesOtherInvestmentsNetOfImpairmentLosses", 1],
  ["200200", "ssmt-mpers:InvestmentInSubisidiaries", "ssmt-mpers:InvestmentsInSubsidiariesUnquotedSharesNetOfImpairmentLosses", 1],
  ["200200", "ssmt-mpers:NoncurrentBorrowings", "ssmt-mpers:NoncurrentPortionOfFinanceLeaseLiabilities", 1],
  ["200200", "ssmt-mpers:NoncurrentBorrowings", "ssmt-mpers:NoncurrentPortionOfLoanFromHoldingCompany", 1],
  ["200200", "ssmt-mpers:NoncurrentBorrowings", "ssmt-mpers:NoncurrentPortionOfLoanFromOtherRelatedCompanies", 1],
  ["200200", "ssmt-mpers:NoncurrentBorrowings", "ssmt-mpers:NoncurrentPortionOfNoncurrentSecuredBankLoansReceived", 1],
  ["200200", "ssmt-mpers:NoncurrentBorrowings", "ssmt-mpers:NoncurrentPortionOfNoncurrentUnsecuredBankLoansReceived", 1],
  ["200200", "ssmt-mpers:NoncurrentBorrowings", "ssmt-mpers:NoncurrentPortionOfOtherNoncurrentBorrowings", 1],
  ["200200", "ssmt-mpers:NoncurrentBorrowings", "ssmt-mpers:NoncurrentPortionOfSecuredConvertibleNotes", 1],
  ["200200", "ssmt-mpers:NoncurrentBorrowings", "ssmt-mpers:NoncurrentPortionOfUnsecuredConvertibleNotes", 1],
  ["200200", "ssmt-mpers:NoncurrentBorrowings", "ssmt-mpers:OtherNoncurrentPortionOfLoanFromAssociates", 1],
  ["200200", "ssmt-mpers:NoncurrentBorrowings", "ssmt-mpers:OtherNoncurrentPortionOfLoanFromJointVentures", 1],
  ["200200", "ssmt-mpers:NoncurrentBorrowings", "ssmt-mpers:OtherNoncurrentPortionOfLoanFromSubsidiaries", 1],
  ["200200", "ssmt-mpers:NoncurrentBorrowings", "ssmt-mpers:OtherNoncurrentPortionOfRedeemablePreferenceShares", 1],
  ["200200", "ssmt-mpers:NoncurrentBorrowings", "ssmt-mpers:OtherNoncurrentSecuredBankLoans", 1],
  ["200200", "ssmt-mpers:NoncurrentBorrowings", "ssmt-mpers:OtherNoncurrentUnsecuredBankLoans", 1],
  ["200200", "ssmt-mpers:NoncurrentNontradePayables", "ssmt-mpers:NoncurrentNontradeAccruals", 1],
  ["200200", "ssmt-mpers:NoncurrentNontradePayables", "ssmt-mpers:NoncurrentNontradeDeferredIncome", 1],
  ["200200", "ssmt-mpers:NoncurrentNontradePayables", "ssmt-mpers:NoncurrentNontradeRetentionPayables", 1],
  ["200200", "ssmt-mpers:NoncurrentNontradePayables", "ssmt-mpers:OtherNoncurrentNontradePayables", 1],
  ["200200", "ssmt-mpers:NoncurrentTradeReceivables", "ssmt-mpers:NoncurrentTradeReceivablesDueFromAssociates", 1],
  ["200200", "ssmt-mpers:NoncurrentTradeReceivables", "ssmt-mpers:NoncurrentTradeReceivablesDueFromHoldingCompany", 1],
  ["200200", "ssmt-mpers:NoncurrentTradeReceivables", "ssmt-mpers:NoncurrentTradeReceivablesDueFromJointVentures", 1],
  ["200200", "ssmt-mpers:NoncurrentTradeReceivables", "ssmt-mpers:NoncurrentTradeReceivablesDueFromRelatedParties", 1],
  ["200200", "ssmt-mpers:NoncurrentTradeReceivables", "ssmt-mpers:NoncurrentTradeReceivablesDueFromSubsidiaries", 1],
  ["200200", "ssmt-mpers:NoncurrentTradeReceivables", "ssmt-mpers:OtherNoncurrentTradeReceivables", 1],
  ["200200", "ssmt-mpers:NondistributableReserves", "ifrs-smes:ReserveOfExchangeDifferencesOnTranslation", 1],
  ["200200", "ssmt-mpers:NondistributableReserves", "ifrs-smes:RevaluationSurplus", 1],
  ["200200", "ssmt-mpers:NondistributableReserves", "ssmt-mpers:CapitalReserve", 1],
  ["200200", "ssmt-mpers:NondistributableReserves", "ssmt-mpers:OtherNondistributableReserves", 1],
  ["200200", "ssmt-mpers:NontradeReceivables", "ssmt-mpers:NontradeDividendReceivables", 1],
  ["200200", "ssmt-mpers:NontradeReceivables", "ssmt-mpers:NontradeInterestReceivables", 1],
  ["200200", "ssmt-mpers:NontradeReceivables", "ssmt-mpers:NontradeLeaseAndHirePurchaseReceivables", 1],
  ["200200", "ssmt-mpers:NontradeReceivables", "ssmt-mpers:NontradeReceivablesDeposits", 1],
  ["200200", "ssmt-mpers:NontradeReceivables", "ssmt-mpers:OtherNontradeReceivables", 1],
  ["200200", "ssmt-mpers:OtherComponentsOfEquity", "ssmt-mpers:EquityComponentOfIrredeemableConvertibleUnsecuredLoanStocks", 1],
  ["200200", "ssmt-mpers:OtherComponentsOfEquity", "ssmt-mpers:EquityComponentOfPreferenceShares", 1],
  ["200200", "ssmt-mpers:OtherComponentsOfEquity", "ssmt-mpers:EquityComponentsOfOtherFinancialInstruments", 1],
  ["200200", "ssmt-mpers:OtherComponentsOfEquity", "ssmt-mpers:PerpetualSukuk", 1],
  ["200200", "ssmt-mpers:OtherCurrentNontradeReceivables", "ssmt-mpers:OtherCurrentMiscellaneousNontradeReceivables", 1],
  ["200200", "ssmt-mpers:OtherCurrentNontradeReceivables", "ssmt-mpers:OtherCurrentNontradeDeposits", 1],
  ["200200", "ssmt-mpers:OtherCurrentNontradeReceivables", "ssmt-mpers:OtherCurrentNontradeDividendReceivables", 1],
  ["200200", "ssmt-mpers:OtherCurrentNontradeReceivables", "ssmt-mpers:OtherCurrentNontradeFinanceIncomeReceivable", 1],
  ["200200", "ssmt-mpers:OtherCurrentNontradeReceivables", "ssmt-mpers:OtherCurrentNontradeLeaseAndHirePurchaseReceivables", 1],
  ["200200", "ssmt-mpers:OtherCurrentPayables", "ssmt-mpers:CurrentNontradePayables", 1],
  ["200200", "ssmt-mpers:OtherCurrentPayables", "ssmt-mpers:OtherCurrentPayablesDueToRelatedParties", 1],
  ["200200", "ssmt-mpers:OtherCurrentPayablesDueToRelatedParties", "ssmt-mpers:OtherCurrentPayablesDueToAssociates", 1],
  ["200200", "ssmt-mpers:OtherCurrentPayablesDueToRelatedParties", "ssmt-mpers:OtherCurrentPayablesDueToHoldingCompany", 1],
  ["200200", "ssmt-mpers:OtherCurrentPayablesDueToRelatedParties", "ssmt-mpers:OtherCurrentPayablesDueToJointVentures", 1],
  ["200200", "ssmt-mpers:OtherCurrentPayablesDueToRelatedParties", "ssmt-mpers:OtherCurrentPayablesDueToOtherRelatedParties", 1],
  ["200200", "ssmt-mpers:OtherCurrentPayablesDueToRelatedParties", "ssmt-mpers:OtherCurrentPayablesDueToSubsidiaries", 1],
  ["200200", "ssmt-mpers:OtherCurrentPrepaymentsAndCurrentAccruedIncome", "ssmt-mpers:OtherCurrentAccruedIncome", 1],
  ["200200", "ssmt-mpers:OtherCurrentPrepaymentsAndCurrentAccruedIncome", "ssmt-mpers:OtherCurrentPrepayments", 1],
  ["200200", "ssmt-mpers:OtherCurrentReceivables", "ssmt-mpers:OtherCurrentNontradeReceivables", 1],
  ["200200", "ssmt-mpers:OtherCurrentReceivables", "ssmt-mpers:OtherCurrentPrepaymentsAndCurrentAccruedIncome", 1],
  ["200200", "ssmt-mpers:OtherCurrentReceivables", "ssmt-mpers:OtherCurrentReceivablesDueFromRelatedParties", 1],
  ["200200", "ssmt-mpers:OtherCurrentReceivablesDueFromRelatedParties", "ssmt-mpers:OtherCurrentReceivablesDueFromAssociates", 1],
  ["200200", "ssmt-mpers:OtherCurrentReceivablesDueFromRelatedParties", "ssmt-mpers:OtherCurrentReceivablesDueFromHoldingCompany", 1],
  ["200200", "ssmt-mpers:OtherCurrentReceivablesDueFromRelatedParties", "ssmt-mpers:OtherCurrentReceivablesDueFromJointVentures", 1],
  ["200200", "ssmt-mpers:OtherCurrentReceivablesDueFromRelatedParties", "ssmt-mpers:OtherCurrentReceivablesDueFromOtherRelatedParties", 1],
  ["200200", "ssmt-mpers:OtherCurrentReceivablesDueFromRelatedParties", "ssmt-mpers:OtherCurrentReceivablesDueFromSubsidiaries", 1],
  ["200200", "ssmt-mpers:OtherNoncurrentNontradeReceivables", "ssmt-mpers:OtherNoncurrentNontradeLeaseAndHirePurchaseReceivables", 1],
  ["200200", "ssmt-mpers:OtherNoncurrentNontradeReceivables", "ssmt-mpers:OtherNoncurrentNontradeMiscellaneous", 1],
  ["200200", "ssmt-mpers:OtherNoncurrentNontradeReceivables", "ssmt-mpers:OtherNoncurrentNontradePrepaymentAndAccruedIncome", 1],
  ["200200", "ssmt-mpers:OtherNoncurrentPayables", "ssmt-mpers:NoncurrentNontradePayables", 1],
  ["200200", "ssmt-mpers:OtherNoncurrentPayables", "ssmt-mpers:OtherNoncurrentPayablesDueToRelatedParties", 1],
  ["200200", "ssmt-mpers:OtherNoncurrentPayablesDueToRelatedParties", "ssmt-mpers:OtherNoncurrentPayablesDueToRelatedCompanies", 1],
  ["200200", "ssmt-mpers:OtherNoncurrentPayablesDueToRelatedParties", "ssmt-mpers:OtherNoncurrentTradePayablesDueToAssociates", 1],
  ["200200", "ssmt-mpers:OtherNoncurrentPayablesDueToRelatedParties", "ssmt-mpers:OtherNoncurrentTradePayablesDueToHoldingCompany", 1],
  ["200200", "ssmt-mpers:OtherNoncurrentPayablesDueToRelatedParties", "ssmt-mpers:OtherNoncurrentTradePayablesDueToJointVentures", 1],
  ["200200", "ssmt-mpers:OtherNoncurrentPayablesDueToRelatedParties", "ssmt-mpers:OtherNoncurrentTradePayablesDueToSubsidiaries", 1],
  ["200200", "ssmt-mpers:OtherNoncurrentReceivables", "ssmt-mpers:OtherNoncurrentNontradeReceivables", 1],
  ["200200", "ssmt-mpers:OtherNoncurrentReceivablesDueFromRelatedParties", "ssmt-mpers:OtherNoncurrentReceivablesDueFromAssociates", 1],
  ["200200", "ssmt-mpers:OtherNoncurrentReceivablesDueFromRelatedParties", "ssmt-mpers:OtherNoncurrentReceivablesDueFromHoldingCompany", 1],
  ["200200", "ssmt-mpers:OtherNoncurrentReceivablesDueFromRelatedParties", "ssmt-mpers:OtherNoncurrentReceivablesDueFromJointVentures", 1],
  ["200200", "ssmt-mpers:OtherNoncurrentReceivablesDueFromRelatedParties", "ssmt-mpers:OtherNoncurrentReceivablesDueFromOtherRelatedParties", 1],
  ["200200", "ssmt-mpers:OtherNoncurrentReceivablesDueFromRelatedParties", "ssmt-mpers:OtherNoncurrentReceivablesDueFromSubsidiaries", 1],
  ["200200", "ssmt-mpers:OtherNontradePayables", "ssmt-mpers:OtherMiscellaneousNontradePayables", 1],
  ["200200", "ssmt-mpers:OtherNontradePayables", "ssmt-mpers:OtherNontradeAccruals", 1],
  ["200200", "ssmt-mpers:OtherNontradePayables", "ssmt-mpers:OtherNontradeDeferredIncome", 1],
  ["200200", "ssmt-mpers:OtherNontradePayables", "ssmt-mpers:OtherNontradeRetentionPayables", 1],
  ["200200", "ssmt-mpers:OtherPayables", "ssmt-mpers:OtherNontradePayables", 1],
  ["200200", "ssmt-mpers:OtherPayables", "ssmt-mpers:OtherPayablesDueToRelatedParties", 1],
  ["200200", "ssmt-mpers:OtherPayablesDueToRelatedParties", "ssmt-mpers:OtherPayablesDueToAssociates", 1],
  ["200200", "ssmt-mpers:OtherPayablesDueToRelatedParties", "ssmt-mpers:OtherPayablesDueToHoldingCompany", 1],
  ["200200", "ssmt-mpers:OtherPayablesDueToRelatedParties", "ssmt-mpers:OtherPayablesDueToJointVentures", 1],
  ["200200", "ssmt-mpers:OtherPayablesDueToRelatedParties", "ssmt-mpers:OtherPayablesDueToOtherRelatedParties", 1],
  ["200200", "ssmt-mpers:OtherPayablesDueToRelatedParties", "ssmt-mpers:OtherPayablesDueToSubsidiaries", 1],
  ["200200", "ssmt-mpers:OtherReceivables", "ssmt-mpers:NontradeReceivables", 1],
  ["200200", "ssmt-mpers:OtherReceivables", "ssmt-mpers:OtherReceivablesDueFromRelatedParties", 1],
  ["200200", "ssmt-mpers:OtherReceivables", "ssmt-mpers:PrepaymentsAndAccruedIncome", 1],
  ["200200", "ssmt-mpers:OtherReceivablesDueFromRelatedParties", "ssmt-mpers:OtherReceivablesDueFromAssociates", 1],
  ["200200", "ssmt-mpers:OtherReceivablesDueFromRelatedParties", "ssmt-mpers:OtherReceivablesDueFromHoldingCompany", 1],
  ["200200", "ssmt-mpers:OtherReceivablesDueFromRelatedParties", "ssmt-mpers:OtherReceivablesDueFromJointVentures", 1],
  ["200200", "ssmt-mpers:OtherReceivablesDueFromRelatedParties", "ssmt-mpers:OtherReceivablesDueFromOtherRelatedParties", 1],
  ["200200", "ssmt-mpers:OtherReceivablesDueFromRelatedParties", "ssmt-mpers:OtherReceivablesDueFromSubsidiaries", 1],
  ["200200", "ssmt-mpers:PrepaymentsAndAccruedIncome", "ssmt-mpers:OtherAccruedIncome", 1],
  ["200200", "ssmt-mpers:PrepaymentsAndAccruedIncome", "ssmt-mpers:OtherPrepayments", 1],
  ["200200", "ssmt-mpers:TradeReceivables", "ssmt-mpers:OtherTradeReceivables", 1],
  ["200200", "ssmt-mpers:TradeReceivables", "ssmt-mpers:ReceivablesFromContractsWithCustomers", 1],
  ["200200", "ssmt-mpers:TradeReceivables", "ssmt-mpers:TradeReceivablesDueFromAssociates", 1],
  ["200200", "ssmt-mpers:TradeReceivables", "ssmt-mpers:TradeReceivablesDueFromHoldingCompany", 1],
  ["200200", "ssmt-mpers:TradeReceivables", "ssmt-mpers:TradeReceivablesDueFromJointVentures", 1],
  ["200200", "ssmt-mpers:TradeReceivables", "ssmt-mpers:TradeReceivablesDueFromOtherRelatedParties", 1],
  ["200200", "ssmt-mpers:TradeReceivables", "ssmt-mpers:TradeReceivablesDueFromSubsidiaries", 1],
  ["200200", "ssmt:CashAndBankBalances", "ifrs-smes:Cash", 1],
  ["200200", "ssmt:CashAndBankBalances", "ifrs-smes:CashEquivalents", 1],
  ["200200", "ssmt:CashAndBankBalances", "ifrs-smes:OtherCashAndCashEquivalents", 1],
  ["300100", "ifrs-smes:ProfitLoss", "ifrs-smes:ProfitLossAttributableToNoncontrollingInterests", 1],
  ["300100", "ifrs-smes:ProfitLoss", "ifrs-smes:ProfitLossAttributableToOwnersOfParent", 1],
  ["300100", "ifrs-smes:ProfitLoss", "ssmt-mpers:ProfitLossAttributableToOtherComponentsOfEquity", 1],
  ["300200", "ifrs-smes:OtherExpenseByNature", "ifrs-smes:DepreciationPropertyPlantAndEquipment", 1],
  ["300200", "ifrs-smes:OtherExpenseByNature", "ssmt-mpers:AmortisationExpense", 1],
  ["300200", "ifrs-smes:OtherExpenseByNature", "ssmt-mpers:AuditorsRemuneration", 1],
  ["300200", "ifrs-smes:OtherExpenseByNature", "ssmt-mpers:DirectorsRemuneration", 1],
  ["300200", "ifrs-smes:OtherExpenseByNature", "ssmt-mpers:LossOnDisposalOfSubsidiariesAssociatesAndJointVentures", 1],
  ["300200", "ifrs-smes:OtherExpenseByNature", "ssmt-mpers:LossOnRevaluationOfFinancialInstruments", 1],
  ["300200", "ifrs-smes:OtherExpenseByNature", "ssmt-mpers:LossesOnDisposalsOfInvestments", 1],
  ["300200", "ifrs-smes:OtherExpenseByNature", "ssmt-mpers:LossesOnDisposalsOfNoncurrentAssets", 1],
  ["300200", "ifrs-smes:OtherExpenseByNature", "ssmt-mpers:LossesOnDisposalsOfPropertyPlantAndEquipment", 1],
  ["300200", "ifrs-smes:OtherExpenseByNature", "ssmt-mpers:NaturalDisasterRelatedExpenses", 1],
  ["300200", "ifrs-smes:OtherExpenseByNature", "ssmt-mpers:OtherMiscellaneousExpenses", 1],
  ["300200", "ifrs-smes:OtherExpenseByNature", "ssmt-mpers:ProvisionForGuaranteeAndWarranties", 1],
  ["300200", "ifrs-smes:OtherExpenseByNature", "ssmt-mpers:ProvisionForLiabilitiesAndCharges", 1],
  ["300200", "ifrs-smes:OtherExpenseByNature", "ssmt-mpers:RentalExpense", 1],
  ["300200", "ifrs-smes:OtherExpenseByNature", "ssmt-mpers:RoyaltyExpense", 1],
  ["300200", "ssmt-mpers:AuditorsRemuneration", "ssmt-mpers:AuditorsRemunerationForAuditServices", 1],
  ["300200", "ssmt-mpers:AuditorsRemuneration", "ssmt-mpers:AuditorsRemunerationForOtherServices", 1],
  ["300200", "ssmt-mpers:DirectorsRemuneration", "ssmt-mpers:BenefitsInKindExpenses", 1],
  ["300200", "ssmt-mpers:DirectorsRemuneration", "ssmt-mpers:BonusToDirectors", 1],
  ["300200", "ssmt-mpers:DirectorsRemuneration", "ssmt-mpers:DirectorsFees", 1],
  ["300200", "ssmt-mpers:DirectorsRemuneration", "ssmt-mpers:KeyManagementPersonnelCompensationSharebasedPayment", 1],
  ["300200", "ssmt-mpers:DirectorsRemuneration", "ssmt-mpers:OtherDirectorsRemuneration", 1],
  ["300200", "ssmt-mpers:DirectorsRemuneration", "ssmt-mpers:PerformanceIncentives", 1],
  ["300200", "ssmt-mpers:DirectorsRemuneration", "ssmt-mpers:RetirementBenefitsDefinedBenefitPlans", 1],
  ["300200", "ssmt-mpers:DirectorsRemuneration", "ssmt-mpers:RetirementBenefitsDefinedContributionPlans", 1],
  ["300200", "ssmt-mpers:DirectorsRemuneration", "ssmt-mpers:WagesAndSalariesToDirectors", 1],
  ["300200", "ssmt-mpers:LossOnDisposalOfSubsidiariesAssociatesAndJointVentures", "ssmt-mpers:LossOnDisposalOfAssociates", 1],
  ["300200", "ssmt-mpers:LossOnDisposalOfSubsidiariesAssociatesAndJointVentures", "ssmt-mpers:LossOnDisposalOfJointVentures", 1],
  ["300200", "ssmt-mpers:LossOnDisposalOfSubsidiariesAssociatesAndJointVentures", "ssmt-mpers:LossOnDisposalOfSubsidiaries", 1],
  ["400100", "ifrs-smes:ComprehensiveIncome", "ifrs-smes:ComprehensiveIncomeAttributableToNoncontrollingInterests", 1],
  ["400100", "ifrs-smes:ComprehensiveIncome", "ifrs-smes:ComprehensiveIncomeAttributableToOwnersOfParent", 1],
  ["500100", "ifrs-smes:AdjustmentsForReconcileProfitLoss", "ifrs-smes:AdjustmentsForAccruedIncomeExpensesNotYetReceivedPaid", -1],
  ["500100", "ifrs-smes:AdjustmentsForReconcileProfitLoss", "ifrs-smes:AdjustmentsForDecreaseIncreaseInInventories", 1],
  ["500100", "ifrs-smes:AdjustmentsForReconcileProfitLoss", "ifrs-smes:AdjustmentsForDecreaseIncreaseInOtherOperatingReceivables", 1],
  ["500100", "ifrs-smes:AdjustmentsForReconcileProfitLoss", "ifrs-smes:AdjustmentsForDecreaseIncreaseInTradeAccountReceivable", 1],
  ["500100", "ifrs-smes:AdjustmentsForReconcileProfitLoss", "ifrs-smes:AdjustmentsForFairValueGainsLosses", 1],
  ["500100", "ifrs-smes:AdjustmentsForReconcileProfitLoss", "ifrs-smes:AdjustmentsForFinanceCosts", 1],
  ["500100", "ifrs-smes:AdjustmentsForReconcileProfitLoss", "ifrs-smes:AdjustmentsForIncomeTaxExpense", 1],
  ["500100", "ifrs-smes:AdjustmentsForReconcileProfitLoss", "ifrs-smes:AdjustmentsForIncreaseDecreaseInOtherOperatingPayables", 1],
  ["500100", "ifrs-smes:AdjustmentsForReconcileProfitLoss", "ifrs-smes:AdjustmentsForIncreaseDecreaseInTradeAccountPayable", 1],
  ["500100", "ifrs-smes:AdjustmentsForReconcileProfitLoss", "ifrs-smes:AdjustmentsForNoncashFinanceCosts", 1],
  ["500100", "ifrs-smes:AdjustmentsForReconcileProfitLoss", "ifrs-smes:AdjustmentsForNoncashIncomeTaxExpense", 1],
  ["500100", "ifrs-smes:AdjustmentsForReconcileProfitLoss", "ifrs-smes:AdjustmentsForProvisions", 1],
  ["500100", "ifrs-smes:AdjustmentsForReconcileProfitLoss", "ifrs-smes:AdjustmentsForSharebasedPayments", 1],
  ["500100", "ifrs-smes:AdjustmentsForReconcileProfitLoss", "ifrs-smes:AdjustmentsForUnrealisedForeignExchangeLossesGains", 1],
  ["500100", "ifrs-smes:AdjustmentsForReconcileProfitLoss", "ifrs-smes:ImpairmentLossRecognisedInProfitOrLossIntangibleAssetsOtherThanGoodwill", 1],
  ["500100", "ifrs-smes:AdjustmentsForReconcileProfitLoss", "ifrs-smes:ImpairmentLossRecognisedInProfitOrLossPropertyPlantAndEquipment", 1],
  ["500100", "ifrs-smes:AdjustmentsForReconcileProfitLoss", "ifrs-smes:OtherAdjustmentsForNoncashItems", 1],
  ["500100", "ifrs-smes:AdjustmentsForReconcileProfitLoss", "ifrs-smes:OtherAdjustmentsForWhichCashEffectsAreInvestingOrFinancingCashFlow", 1],
  ["500100", "ifrs-smes:AdjustmentsForReconcileProfitLoss", "ifrs-smes:OtherAdjustmentsToReconcileProfitLoss", 1],
  ["500100", "ifrs-smes:AdjustmentsForReconcileProfitLoss", "ifrs-smes:ReversalOfInventoryWritedown", 1],
  ["500100", "ifrs-smes:AdjustmentsForReconcileProfitLoss", "ssmt-mpers:AdjustmentsForAmortisationExpense", 1],
  ["500100", "ifrs-smes:AdjustmentsForReconcileProfitLoss", "ssmt-mpers:AdjustmentsForDepreciationExpense", 1],
  ["500100", "ifrs-smes:AdjustmentsForReconcileProfitLoss", "ssmt-mpers:AdjustmentsForDividendIncome", -1],
  ["500100", "ifrs-smes:AdjustmentsForReconcileProfitLoss", "ssmt-mpers:AdjustmentsForFinanceIncome", -1],
  ["500100", "ifrs-smes:AdjustmentsForReconcileProfitLoss", "ssmt-mpers:AdjustmentsForShareOfProfitOfEquityAccountedAssociatesAndJointVenturesNetOfTax", -1],
  ["500100", "ifrs-smes:AdjustmentsForReconcileProfitLoss", "ssmt-mpers:GainsLossesOnDisposalOfOtherInvestments", -1],
  ["500100", "ifrs-smes:AdjustmentsForReconcileProfitLoss", "ssmt-mpers:GainsLossesOnDisposalsOfInvestmentProperties", -1],
  ["500100", "ifrs-smes:AdjustmentsForReconcileProfitLoss", "ssmt-mpers:GainsLossesOnDisposalsOfPropertyPlantAndEquipment", -1],
  ["500100", "ifrs-smes:CashAndCashEquivalents", "ifrs-smes:BankOverdraftsClassifiedAsCashEquivalents", -1],
  ["500100", "ifrs-smes:CashAndCashEquivalents", "ssmt:CashAndBankBalances", 1],
  ["500100", "ifrs-smes:CashAndCashEquivalents", "ssmt:OtherAdjustmentsToReconcileCashAndCashEquivalents", 1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInFinancingActivities", "ifrs-smes:DividendsPaidClassifiedAsFinancingActivities", -1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInFinancingActivities", "ifrs-smes:InterestPaidClassifiedAsFinancingActivities", -1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInFinancingActivities", "ifrs-smes:OtherInflowsOutflowsOfCashClassifiedAsFinancingActivities", 1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInFinancingActivities", "ifrs-smes:PaymentsOfFinanceLeaseLiabilitiesClassifiedAsFinancingActivities", -1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInFinancingActivities", "ifrs-smes:PaymentsOfOtherEquityInstruments", -1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInFinancingActivities", "ifrs-smes:PaymentsToAcquireOrRedeemEntitysShares", -1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInFinancingActivities", "ifrs-smes:ProceedsFromBorrowingsClassifiedAsFinancingActivities", 1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInFinancingActivities", "ifrs-smes:ProceedsFromIssuingOtherEquityInstruments", 1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInFinancingActivities", "ifrs-smes:ProceedsFromIssuingShares", 1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInFinancingActivities", "ifrs-smes:RepaymentsOfBorrowingsClassifiedAsFinancingActivities", -1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInFinancingActivities", "ssmt-mpers:RepaymentOfLoanFromAssociate", -1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInInvestingActivities", "ifrs-smes:CashAdvancesAndLoansMadeToOtherPartiesClassifiedAsInvestingActivities", -1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInInvestingActivities", "ifrs-smes:CashFlowsFromLosingControlOfSubsidiariesOrOtherBusinessesClassifiedAsInvestingActivities", 1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInInvestingActivities", "ifrs-smes:CashFlowsUsedInObtainingControlOfSubsidiariesOrOtherBusinessesClassifiedAsInvestingActivities", -1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInInvestingActivities", "ifrs-smes:CashPaymentsForFutureContractsForwardContractsOptionContractsAndSwapContractsClassifiedAsInvestingActivities", -1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInInvestingActivities", "ifrs-smes:CashReceiptsFromFutureContractsForwardContractsOptionContractsAndSwapContractsClassifiedAsInvestingActivities", 1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInInvestingActivities", "ifrs-smes:CashReceiptsFromRepaymentOfAdvancesAndLoansMadeToOtherPartiesClassifiedAsInvestingActivities", 1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInInvestingActivities", "ifrs-smes:DividendsReceivedClassifiedAsInvestingActivities", 1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInInvestingActivities", "ifrs-smes:InterestReceivedClassifiedAsInvestingActivities", 1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInInvestingActivities", "ifrs-smes:OtherCashPaymentsToAcquireEquityOrDebtInstrumentsOfOtherEntitiesClassifiedAsInvestingActivities", -1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInInvestingActivities", "ifrs-smes:OtherCashPaymentsToAcquireInterestsInJointVenturesClassifiedAsInvestingActivities", -1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInInvestingActivities", "ifrs-smes:OtherCashReceiptsFromSalesOfEquityOrDebtInstrumentsOfOtherEntitiesClassifiedAsInvestingActivities", 1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInInvestingActivities", "ifrs-smes:OtherCashReceiptsFromSalesOfInterestsInJointVenturesClassifiedAsInvestingActivities", 1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInInvestingActivities", "ifrs-smes:OtherInflowsOutflowsOfCashClassifiedAsInvestingActivities", 1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInInvestingActivities", "ifrs-smes:ProceedsFromOtherLongtermAssetsClassifiedAsInvestingActivities", 1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInInvestingActivities", "ifrs-smes:ProceedsFromSalesOfIntangibleAssetsClassifiedAsInvestingActivities", 1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInInvestingActivities", "ifrs-smes:ProceedsFromSalesOfPropertyPlantAndEquipmentClassifiedAsInvestingActivities", 1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInInvestingActivities", "ifrs-smes:PurchaseOfIntangibleAssetsClassifiedAsInvestingActivities", -1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInInvestingActivities", "ifrs-smes:PurchaseOfOtherLongtermAssetsClassifiedAsInvestingActivities", -1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInInvestingActivities", "ifrs-smes:PurchaseOfPropertyPlantAndEquipmentClassifiedAsInvestingActivities", -1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInOperatingActivities", "ifrs-smes:DividendsPaidClassifiedAsOperatingActivities", 1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInOperatingActivities", "ifrs-smes:DividendsReceivedClassifiedAsOperatingActivities", 1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInOperatingActivities", "ifrs-smes:IncomeTaxesPaidRefundClassifiedAsOperatingActivities", 1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInOperatingActivities", "ifrs-smes:InterestPaidClassifiedAsOperatingActivities", 1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInOperatingActivities", "ifrs-smes:InterestReceivedClassifiedAsOperatingActivities", 1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInOperatingActivities", "ifrs-smes:OtherCashPaymentsFromOperatingActivities", 1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInOperatingActivities", "ifrs-smes:OtherCashReceiptsFromOperatingActivities", 1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInOperatingActivities", "ifrs-smes:OtherInflowsOutflowsOfCashClassifiedAsOperatingActivities", 1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInOperatingActivities", "ifrs-smes:PaymentsToAndOnBehalfOfEmployees", 1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInOperatingActivities", "ifrs-smes:PaymentsToSuppliersForGoodsAndServices", 1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInOperatingActivities", "ifrs-smes:ReceiptsFromRoyaltiesFeesCommissionsAndOtherRevenue", 1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInOperatingActivities", "ifrs-smes:ReceiptsFromSalesOfGoodsAndRenderingOfServices", 1],
  ["500100", "ifrs-smes:CashFlowsFromUsedInOperatingActivities", "ssmt-mpers:CashFlowsFromUsedInOperations", 1],
  ["500100", "ifrs-smes:IncreaseDecreaseInCashAndCashEquivalents", "ifrs-smes:EffectOfExchangeRateChangesOnCashAndCashEquivalents", 1],
  ["500100", "ifrs-smes:IncreaseDecreaseInCashAndCashEquivalents", "ifrs-smes:IncreaseDecreaseInCashAndCashEquivalentsBeforeEffectOfExchangeRateChanges", 1],
  ["500100", "ifrs-smes:IncreaseDecreaseInCashAndCashEquivalentsBeforeEffectOfExchangeRateChanges", "ifrs-smes:CashFlowsFromUsedInFinancingActivities", 1],
  ["500100", "ifrs-smes:IncreaseDecreaseInCashAndCashEquivalentsBeforeEffectOfExchangeRateChanges", "ifrs-smes:CashFlowsFromUsedInInvestingActivities", 1],
  ["500100", "ifrs-smes:IncreaseDecreaseInCashAndCashEquivalentsBeforeEffectOfExchangeRateChanges", "ifrs-smes:CashFlowsFromUsedInOperatingActivities", 1],
  ["500100", "ssmt-mpers:AggregateProfitLossBeforeTax", "ifrs-smes:ProfitLossBeforeTax", 1],
  ["500100", "ssmt-mpers:AggregateProfitLossBeforeTax", "ifrs-smes:ProfitLossFromDiscontinuedOperations", 1],
  ["500100", "ssmt-mpers:CashFlowsFromUsedInOperations", "ifrs-smes:AdjustmentsForReconcileProfitLoss", 1],
  ["500100", "ssmt-mpers:CashFlowsFromUsedInOperations", "ssmt-mpers:AggregateProfitLossBeforeTax", 1],
  ["610000", "ifrs-smes:ChangesInEquity", "ifrs-smes:ComprehensiveIncome", 1],
  ["610000", "ifrs-smes:ChangesInEquity", "ifrs-smes:DividendsPaid", -1],
  ["610000", "ifrs-smes:ChangesInEquity", "ifrs-smes:IncreaseDecreaseThroughSharebasedPaymentTransactions", 1],
  ["610000", "ifrs-smes:ChangesInEquity", "ifrs-smes:IncreaseDecreaseThroughTransfersAndOtherChangesEquity", 1],
  ["610000", "ifrs-smes:ChangesInEquity", "ifrs-smes:IncreaseDecreaseThroughTreasuryShareTransactions", 1],
  ["610000", "ifrs-smes:ChangesInEquity", "ifrs-smes:IssueOfEquity", 1],
  ["610000", "ifrs-smes:ChangesInEquity", "ssmt-mpers:IncreaseDecreaseThroughAcquisitionOfSubsidiary", 1],
  ["610000", "ifrs-smes:ChangesInEquity", "ssmt-mpers:IncreaseDecreaseThroughConversionOfConvertibleInstruments", 1],
  ["610000", "ifrs-smes:ChangesInEquity", "ssmt-mpers:IncreaseDecreaseThroughTransactionsWithOwners", 1],
  ["610000", "ifrs-smes:ChangesInEquity", "ssmt-mpers:IssueOfConvertibleInstruments", 1],
  ["610000", "ifrs-smes:ComprehensiveIncome", "ifrs-smes:OtherComprehensiveIncome", 1],
  ["610000", "ifrs-smes:ComprehensiveIncome", "ifrs-smes:ProfitLoss", 1],
  ["620000", "ssmt-mpers:AggregateProfitLoss", "ifrs-smes:ProfitLoss", 1],
  ["620000", "ssmt-mpers:IncreaseDecreaseInRetainedEarnings", "ifrs-smes:DividendsPaid", -1],
  ["620000", "ssmt-mpers:IncreaseDecreaseInRetainedEarnings", "ssmt-mpers:AggregateProfitLoss", 1],
];

/** Totals read as note lines and mapped into SSM's tree (see mbrs-extract). */
export interface TagNode { c: string; parent: string; label: string; field: string; leaf: boolean }
export interface TagTree { root: string; rootField: string; rootLabel: string; nodes: TagNode[] }
export const TAG_TREES: TagTree[] = [
 {
  "root": "ifrs-smes:PropertyPlantAndEquipment",
  "rootField": "propertyPlantAndEquipment",
  "rootLabel": "Property, plant and equipment",
  "nodes": [
   {
    "c": "ifrs-smes:LandAndBuildings",
    "parent": "ifrs-smes:PropertyPlantAndEquipment",
    "label": "Land and buildings",
    "field": "buildings",
    "leaf": false
   },
   {
    "c": "ifrs-smes:Land",
    "parent": "ifrs-smes:LandAndBuildings",
    "label": "Land",
    "field": "",
    "leaf": false
   },
   {
    "c": "ssmt-mpers:FreeholdLand",
    "parent": "ifrs-smes:Land",
    "label": "Freehold land",
    "field": "",
    "leaf": true
   },
   {
    "c": "ssmt-mpers:LongtermLeaseholdLand",
    "parent": "ifrs-smes:Land",
    "label": "Long term leasehold land",
    "field": "",
    "leaf": true
   },
   {
    "c": "ssmt-mpers:ShorttermLeaseholdLand",
    "parent": "ifrs-smes:Land",
    "label": "Short term leasehold land",
    "field": "",
    "leaf": true
   },
   {
    "c": "ifrs-smes:Buildings",
    "parent": "ifrs-smes:LandAndBuildings",
    "label": "Buildings",
    "field": "",
    "leaf": false
   },
   {
    "c": "ssmt-mpers:BuildingOnFreeholdLand",
    "parent": "ifrs-smes:Buildings",
    "label": "Building on freehold land",
    "field": "",
    "leaf": true
   },
   {
    "c": "ssmt-mpers:BuildingOnLongtermLeaseholdLand",
    "parent": "ifrs-smes:Buildings",
    "label": "Building on long term leasehold land",
    "field": "",
    "leaf": true
   },
   {
    "c": "ssmt-mpers:BuildingOnShorttermLeaseholdLand",
    "parent": "ifrs-smes:Buildings",
    "label": "Building on short term leasehold land",
    "field": "",
    "leaf": true
   },
   {
    "c": "ssmt-mpers:LeasedProperties",
    "parent": "ifrs-smes:Buildings",
    "label": "Leased properties",
    "field": "",
    "leaf": true
   },
   {
    "c": "ifrs-smes:Machinery",
    "parent": "ifrs-smes:PropertyPlantAndEquipment",
    "label": "Machinery",
    "field": "",
    "leaf": true
   },
   {
    "c": "ifrs-smes:Vehicles",
    "parent": "ifrs-smes:PropertyPlantAndEquipment",
    "label": "Vehicles",
    "field": "vehicles",
    "leaf": true
   },
   {
    "c": "ssmt-mpers:OfficeEquipmentFixtureAndFittings",
    "parent": "ifrs-smes:PropertyPlantAndEquipment",
    "label": "Office equipment, fixture and fittings",
    "field": "officeEquipment",
    "leaf": true
   },
   {
    "c": "ssmt-mpers:PlantAndEquipment",
    "parent": "ifrs-smes:PropertyPlantAndEquipment",
    "label": "Plant and equipment",
    "field": "plantAndEquipment",
    "leaf": true
   },
   {
    "c": "ifrs-smes:ConstructionInProgress",
    "parent": "ifrs-smes:PropertyPlantAndEquipment",
    "label": "Construction in progress",
    "field": "",
    "leaf": true
   },
   {
    "c": "ifrs-smes:OtherPropertyPlantAndEquipment",
    "parent": "ifrs-smes:PropertyPlantAndEquipment",
    "label": "Other property, plant and equipment",
    "field": "otherPropertyPlantAndEquipment",
    "leaf": true
   }
  ]
 },
 {
  "root": "ifrs-smes:InvestmentProperty",
  "rootField": "investmentProperty",
  "rootLabel": "Investment property at fair value through profit or loss",
  "nodes": [
   {
    "c": "ssmt-mpers:InvestmentPropertyFreeholdLandAndBuilding",
    "parent": "ifrs-smes:InvestmentProperty",
    "label": "Freehold land and building",
    "field": "investmentPropertyFreehold",
    "leaf": true
   },
   {
    "c": "ssmt-mpers:InvestmentPropertyLongtermLeaseholdLand",
    "parent": "ifrs-smes:InvestmentProperty",
    "label": "Investment property long-term leasehold land",
    "field": "",
    "leaf": true
   },
   {
    "c": "ssmt-mpers:InvestmentPropertyShorttermLeaseholdLand",
    "parent": "ifrs-smes:InvestmentProperty",
    "label": "Investment property short-term leasehold land",
    "field": "",
    "leaf": true
   },
   {
    "c": "ssmt-mpers:InvestmentPropertyBuildingUnderConstruction",
    "parent": "ifrs-smes:InvestmentProperty",
    "label": "Building under construction",
    "field": "",
    "leaf": true
   },
   {
    "c": "ssmt-mpers:OtherInvestmentProperty",
    "parent": "ifrs-smes:InvestmentProperty",
    "label": "Other investment property",
    "field": "investmentPropertyOther",
    "leaf": true
   }
  ]
 },
 {
  "root": "ifrs-smes:InventoriesTotal",
  "rootField": "inventories",
  "rootLabel": "Inventories",
  "nodes": [
   {
    "c": "ssmt-mpers:RawMaterials",
    "parent": "ifrs-smes:InventoriesTotal",
    "label": "Raw materials",
    "field": "",
    "leaf": true
   },
   {
    "c": "ifrs-smes:WorkInProgress",
    "parent": "ifrs-smes:InventoriesTotal",
    "label": "Current work in progress",
    "field": "",
    "leaf": true
   },
   {
    "c": "ssmt-mpers:FinishedGoods",
    "parent": "ifrs-smes:InventoriesTotal",
    "label": "Finished goods",
    "field": "",
    "leaf": true
   },
   {
    "c": "ssmt-mpers:SpareParts",
    "parent": "ifrs-smes:InventoriesTotal",
    "label": "Spare parts",
    "field": "",
    "leaf": true
   },
   {
    "c": "ssmt-mpers:OtherInventories",
    "parent": "ifrs-smes:InventoriesTotal",
    "label": "Other inventories",
    "field": "",
    "leaf": true
   }
  ]
 }
];

/** SSM's label for each concept above, for messages a filer can read. */
export const MBRS_CALC_LABELS: Record<string, string> = {
  "ifrs-smes:AdjustmentsForAccruedIncomeExpensesNotYetReceivedPaid": "Adjustments for accrued income (expenses) not yet received (paid)",
  "ifrs-smes:AdjustmentsForDecreaseIncreaseInInventories": "Adjustments for decrease (increase) in inventories",
  "ifrs-smes:AdjustmentsForDecreaseIncreaseInOtherOperatingReceivables": "Adjustments for decrease (increase) in other operating receivables",
  "ifrs-smes:AdjustmentsForDecreaseIncreaseInTradeAccountReceivable": "Adjustments for decrease (increase) in trade accounts receivable",
  "ifrs-smes:AdjustmentsForFairValueGainsLosses": "Adjustments for fair value losses (gains)",
  "ifrs-smes:AdjustmentsForFinanceCosts": "Adjustments for finance costs",
  "ifrs-smes:AdjustmentsForIncomeTaxExpense": "Adjustments for income tax expense",
  "ifrs-smes:AdjustmentsForIncreaseDecreaseInOtherOperatingPayables": "Adjustments for increase (decrease) in other operating payables",
  "ifrs-smes:AdjustmentsForIncreaseDecreaseInTradeAccountPayable": "Adjustments for increase (decrease) in trade accounts payable",
  "ifrs-smes:AdjustmentsForNoncashFinanceCosts": "Adjustments for non-cash finance costs",
  "ifrs-smes:AdjustmentsForNoncashIncomeTaxExpense": "Adjustments for non-cash income tax expense",
  "ifrs-smes:AdjustmentsForProvisions": "Adjustments for provisions",
  "ifrs-smes:AdjustmentsForReconcileProfitLoss": "Adjustments to reconcile profit (loss)",
  "ifrs-smes:AdjustmentsForSharebasedPayments": "Adjustments for share-based payments",
  "ifrs-smes:AdjustmentsForUnrealisedForeignExchangeLossesGains": "Adjustments for unrealised foreign exchange losses (gains)",
  "ifrs-smes:BalancesWithBanks": "Balances with banks",
  "ifrs-smes:BankOverdraftsClassifiedAsCashEquivalents": "Bank overdrafts",
  "ifrs-smes:BankingArrangementsClassifiedAsCashEquivalents": "Other banking arrangements, classified as cash equivalents",
  "ifrs-smes:Borrowings": "Borrowings",
  "ifrs-smes:Buildings": "Buildings",
  "ifrs-smes:Cash": "Cash",
  "ifrs-smes:CashAdvancesAndLoansMadeToOtherPartiesClassifiedAsInvestingActivities": "Cash advances and loans made to other parties, classified as investing activities",
  "ifrs-smes:CashAndCashEquivalents": "Cash and cash equivalents",
  "ifrs-smes:CashEquivalents": "Cash equivalents",
  "ifrs-smes:CashFlowsFromLosingControlOfSubsidiariesOrOtherBusinessesClassifiedAsInvestingActivities": "Cash flows from losing control of subsidiaries or other businesses, classified as investing activities",
  "ifrs-smes:CashFlowsFromUsedInFinancingActivities": "Cash flows from (used in) financing activities",
  "ifrs-smes:CashFlowsFromUsedInInvestingActivities": "Cash flows from (used in) investing activities",
  "ifrs-smes:CashFlowsFromUsedInOperatingActivities": "Cash flows from (used in) operating activities",
  "ifrs-smes:CashFlowsUsedInObtainingControlOfSubsidiariesOrOtherBusinessesClassifiedAsInvestingActivities": "Cash flows used in obtaining control of subsidiaries or other businesses, classified as investing activities",
  "ifrs-smes:CashOnHand": "Cash on hand",
  "ifrs-smes:CashPaymentsForFutureContractsForwardContractsOptionContractsAndSwapContractsClassifiedAsInvestingActivities": "Cash payments for futures contracts, forward contracts, option contracts and swap contracts, classified as investing activities",
  "ifrs-smes:CashReceiptsFromFutureContractsForwardContractsOptionContractsAndSwapContractsClassifiedAsInvestingActivities": "Cash receipts from futures contracts, forward contracts, option contracts and swap contracts, classified as investing activities",
  "ifrs-smes:CashReceiptsFromRepaymentOfAdvancesAndLoansMadeToOtherPartiesClassifiedAsInvestingActivities": "Cash receipts from repayment of advances and loans made to other parties, classified as investing activities",
  "ifrs-smes:ChangesInEquity": "Increase (decrease) in equity",
  "ifrs-smes:ComprehensiveIncome": "Comprehensive income",
  "ifrs-smes:ComprehensiveIncomeAttributableToNoncontrollingInterests": "Comprehensive income, attributable to non-controlling interests",
  "ifrs-smes:ComprehensiveIncomeAttributableToOwnersOfParent": "Comprehensive income, attributable to owners of parent",
  "ifrs-smes:ConstructionInProgress": "Construction in progress",
  "ifrs-smes:CopyrightsPatentsAndOtherIndustrialPropertyRightsServiceAndOperatingRights": "Copyrights, patents and other industrial property rights, service and operating rights",
  "ifrs-smes:CurrentAssets": "Current assets",
  "ifrs-smes:CurrentLiabilities": "Current liabilities",
  "ifrs-smes:CurrentProvisions": "Current provisions",
  "ifrs-smes:CurrentProvisionsForEmployeeBenefits": "Current provisions for employee benefits",
  "ifrs-smes:CurrentTaxAssetsCurrent": "Current tax assets, current",
  "ifrs-smes:CurrentTaxLiabilitiesCurrent": "Current tax liabilities, current",
  "ifrs-smes:DeferredIncomeClassifiedAsCurrent": "Deferred income classified as current",
  "ifrs-smes:DeferredIncomeClassifiedAsNoncurrent": "Deferred income classified as non-current",
  "ifrs-smes:DeferredTaxAssets": "Deferred tax assets",
  "ifrs-smes:DeferredTaxLiabilities": "Deferred tax liabilities",
  "ifrs-smes:DepreciationPropertyPlantAndEquipment": "Depreciation, property, plant and equipment",
  "ifrs-smes:DividendsPaid": "Dividends recognised as distributions to owners",
  "ifrs-smes:DividendsPaidClassifiedAsFinancingActivities": "Dividends paid, classified as financing activities",
  "ifrs-smes:DividendsPaidClassifiedAsOperatingActivities": "Dividends paid, classified as operating activities",
  "ifrs-smes:DividendsReceivedClassifiedAsInvestingActivities": "Dividends received, classified as investing activities",
  "ifrs-smes:DividendsReceivedClassifiedAsOperatingActivities": "Dividends received, classified as operating activities",
  "ifrs-smes:EffectOfExchangeRateChangesOnCashAndCashEquivalents": "Effect of exchange rate changes on cash and cash equivalents",
  "ifrs-smes:EquityAttributableToOwnersOfParent": "Equity attributable to owners",
  "ifrs-smes:Goodwill": "Goodwill",
  "ifrs-smes:ImpairmentLossRecognisedInProfitOrLossIntangibleAssetsOtherThanGoodwill": "Impairment loss recognised in profit or loss, intangible assets other than goodwill",
  "ifrs-smes:ImpairmentLossRecognisedInProfitOrLossPropertyPlantAndEquipment": "Impairment loss recognised in profit or loss, property, plant and equipment",
  "ifrs-smes:IncomeTaxesPaidRefundClassifiedAsOperatingActivities": "Income taxes paid (refund), classified as operating activities",
  "ifrs-smes:IncreaseDecreaseInCashAndCashEquivalents": "Increase (decrease) in cash and cash equivalents",
  "ifrs-smes:IncreaseDecreaseInCashAndCashEquivalentsBeforeEffectOfExchangeRateChanges": "Increase (decrease) in cash and cash equivalents before effect of exchange rate changes",
  "ifrs-smes:IncreaseDecreaseThroughSharebasedPaymentTransactions": "Increase (decrease) through share-based payment transactions, equity",
  "ifrs-smes:IncreaseDecreaseThroughTransfersAndOtherChangesEquity": "Increase (decrease) through other changes, equity",
  "ifrs-smes:IncreaseDecreaseThroughTreasuryShareTransactions": "Increase (decrease) through treasury share transactions, equity",
  "ifrs-smes:IntangibleAssetsAndGoodwill": "Intangible assets and goodwill",
  "ifrs-smes:IntangibleAssetsOtherThanGoodwill": "Intangible assets other than goodwill",
  "ifrs-smes:InterestPaidClassifiedAsFinancingActivities": "Interest paid, classified as financing activities",
  "ifrs-smes:InterestPaidClassifiedAsOperatingActivities": "Interest paid, classified as operating activities",
  "ifrs-smes:InterestReceivedClassifiedAsInvestingActivities": "Interest received, classified as investing activities",
  "ifrs-smes:InterestReceivedClassifiedAsOperatingActivities": "Interest received, classified as operating activities",
  "ifrs-smes:InventoriesTotal": "Inventories",
  "ifrs-smes:InvestmentProperty": "Investment property at fair value through profit or loss",
  "ifrs-smes:InvestmentsInAssociates": "Investments in associates",
  "ifrs-smes:InvestmentsInJointVentures": "Investments in joint ventures",
  "ifrs-smes:IssueOfEquity": "Issue of equity",
  "ifrs-smes:IssuedCapital": "Issued capital",
  "ifrs-smes:Land": "Land",
  "ifrs-smes:LandAndBuildings": "Land and buildings",
  "ifrs-smes:LegalProceedingsProvision": "Legal proceedings provision",
  "ifrs-smes:LongtermLegalProceedingsProvision": "Non-current legal proceedings provision",
  "ifrs-smes:LongtermMiscellaneousOtherProvisions": "Non-current miscellaneous other provisions",
  "ifrs-smes:LongtermOnerousContractsProvision": "Non-current onerous contracts provision",
  "ifrs-smes:LongtermRestructuringProvision": "Non-current restructuring provision",
  "ifrs-smes:LongtermWarrantyProvision": "Non-current warranty provision",
  "ifrs-smes:Machinery": "Machinery",
  "ifrs-smes:NoncurrentAssets": "Non-current assets",
  "ifrs-smes:NoncurrentLiabilities": "Non-current liabilities",
  "ifrs-smes:NoncurrentPayables": "Trade and other non-current payables",
  "ifrs-smes:NoncurrentPayablesToTradeSuppliers": "Non-current trade payables",
  "ifrs-smes:NoncurrentProvisions": "Non-current provisions",
  "ifrs-smes:NoncurrentProvisionsForEmployeeBenefits": "Non-current provisions for employee benefits",
  "ifrs-smes:NoncurrentReceivables": "Trade and other non-current receivables",
  "ifrs-smes:OnerousContractsProvision": "Onerous contracts provision",
  "ifrs-smes:OtherAdjustmentsForNoncashItems": "Other adjustments for non-cash items",
  "ifrs-smes:OtherAdjustmentsForWhichCashEffectsAreInvestingOrFinancingCashFlow": "Other adjustments for which cash effects are investing or financing cash flow",
  "ifrs-smes:OtherAdjustmentsToReconcileProfitLoss": "Other adjustments to reconcile profit (loss)",
  "ifrs-smes:OtherCashAndCashEquivalents": "Other cash and cash equivalents",
  "ifrs-smes:OtherCashPaymentsFromOperatingActivities": "Other cash payments from operating activities",
  "ifrs-smes:OtherCashPaymentsToAcquireEquityOrDebtInstrumentsOfOtherEntitiesClassifiedAsInvestingActivities": "Other cash payments to acquire equity or debt instruments of other entities, classified as investing activities",
  "ifrs-smes:OtherCashPaymentsToAcquireInterestsInJointVenturesClassifiedAsInvestingActivities": "Other cash payments to acquire interests in joint ventures, classified as investing activities",
  "ifrs-smes:OtherCashReceiptsFromOperatingActivities": "Other cash receipts from operating activities",
  "ifrs-smes:OtherCashReceiptsFromSalesOfEquityOrDebtInstrumentsOfOtherEntitiesClassifiedAsInvestingActivities": "Other cash receipts from sales of equity or debt instruments of other entities, classified as investing activities",
  "ifrs-smes:OtherCashReceiptsFromSalesOfInterestsInJointVenturesClassifiedAsInvestingActivities": "Other cash receipts from sales of interests in joint ventures, classified as investing activities",
  "ifrs-smes:OtherComprehensiveIncome": "Other comprehensive income",
  "ifrs-smes:OtherExpenseByNature": "Other expenses, by nature",
  "ifrs-smes:OtherInflowsOutflowsOfCashClassifiedAsFinancingActivities": "Other inflows (outflows) of cash, classified as financing activities",
  "ifrs-smes:OtherInflowsOutflowsOfCashClassifiedAsInvestingActivities": "Other inflows (outflows) of cash, classified as investing activities",
  "ifrs-smes:OtherInflowsOutflowsOfCashClassifiedAsOperatingActivities": "Other inflows (outflows) of cash, classified as operating activities",
  "ifrs-smes:OtherIntangibleAssets": "Other intangible assets",
  "ifrs-smes:OtherPropertyPlantAndEquipment": "Other property, plant and equipment",
  "ifrs-smes:OtherProvisions": "Other provisions",
  "ifrs-smes:OtherReserves": "Reserves",
  "ifrs-smes:OtherShorttermProvisions": "Other current provisions",
  "ifrs-smes:PaymentsOfFinanceLeaseLiabilitiesClassifiedAsFinancingActivities": "Payments of finance lease liabilities, classified as financing activities",
  "ifrs-smes:PaymentsOfOtherEquityInstruments": "Payments of other equity instruments",
  "ifrs-smes:PaymentsToAcquireOrRedeemEntitysShares": "Payments to acquire or redeem entity's shares",
  "ifrs-smes:PaymentsToAndOnBehalfOfEmployees": "Payments to and on behalf of employees",
  "ifrs-smes:PaymentsToSuppliersForGoodsAndServices": "Payments to suppliers for goods and services",
  "ifrs-smes:ProceedsFromBorrowingsClassifiedAsFinancingActivities": "Proceeds from borrowings, classified as financing activities",
  "ifrs-smes:ProceedsFromIssuingOtherEquityInstruments": "Proceeds from issuing other equity instruments",
  "ifrs-smes:ProceedsFromIssuingShares": "Proceeds from issuing shares",
  "ifrs-smes:ProceedsFromOtherLongtermAssetsClassifiedAsInvestingActivities": "Proceeds from sales of other long-term assets, classified as investing activities",
  "ifrs-smes:ProceedsFromSalesOfIntangibleAssetsClassifiedAsInvestingActivities": "Proceeds from sales of intangible assets, classified as investing activities",
  "ifrs-smes:ProceedsFromSalesOfPropertyPlantAndEquipmentClassifiedAsInvestingActivities": "Proceeds from sales of property, plant and equipment, classified as investing activities",
  "ifrs-smes:ProfitLoss": "Profit (loss)",
  "ifrs-smes:ProfitLossAttributableToNoncontrollingInterests": "Profit (loss), attributable to non-controlling interests",
  "ifrs-smes:ProfitLossAttributableToOwnersOfParent": "Profit (loss), attributable to owners of parent",
  "ifrs-smes:ProfitLossBeforeTax": "Profit (loss) before tax",
  "ifrs-smes:ProfitLossFromDiscontinuedOperations": "Profit (loss) from discontinued operations",
  "ifrs-smes:PropertyPlantAndEquipment": "Property, plant and equipment",
  "ifrs-smes:Provisions": "Provisions",
  "ifrs-smes:ProvisionsForEmployeeBenefits": "Provisions for employee benefits",
  "ifrs-smes:PurchaseOfIntangibleAssetsClassifiedAsInvestingActivities": "Purchase of intangible assets, classified as investing activities",
  "ifrs-smes:PurchaseOfOtherLongtermAssetsClassifiedAsInvestingActivities": "Purchase of other long-term assets, classified as investing activities",
  "ifrs-smes:PurchaseOfPropertyPlantAndEquipmentClassifiedAsInvestingActivities": "Purchase of property, plant and equipment, classified as investing activities",
  "ifrs-smes:ReceiptsFromRoyaltiesFeesCommissionsAndOtherRevenue": "Receipts from royalties, fees, commissions and other revenue",
  "ifrs-smes:ReceiptsFromSalesOfGoodsAndRenderingOfServices": "Receipts from sales of goods and rendering of services",
  "ifrs-smes:RepaymentsOfBorrowingsClassifiedAsFinancingActivities": "Repayments of borrowings, classified as financing activities",
  "ifrs-smes:ReserveOfExchangeDifferencesOnTranslation": "Reserve of exchange differences on translation",
  "ifrs-smes:RestructuringProvision": "Restructuring provision",
  "ifrs-smes:RetainedEarnings": "Retained earnings",
  "ifrs-smes:RevaluationSurplus": "Revaluation surplus",
  "ifrs-smes:ReversalOfInventoryWritedown": "Reversal of inventory write-down",
  "ifrs-smes:ShorttermBorrowings": "Current borrowings",
  "ifrs-smes:ShorttermDepositsClassifiedAsCashEquivalents": "Short-term deposits, classified as cash equivalents",
  "ifrs-smes:ShorttermInvestmentsClassifiedAsCashEquivalents": "Short-term investments, classified as cash equivalents",
  "ifrs-smes:ShorttermLegalProceedingsProvision": "Current legal proceedings provision",
  "ifrs-smes:ShorttermOnerousContractsProvision": "Current onerous contracts provision",
  "ifrs-smes:ShorttermRestructuringProvision": "Current restructuring provision",
  "ifrs-smes:ShorttermWarrantyProvision": "Current warranty provision",
  "ifrs-smes:TradeAndOtherCurrentPayables": "Trade and other current payables",
  "ifrs-smes:TradeAndOtherCurrentPayablesToTradeSuppliers": "Current trade payables",
  "ifrs-smes:TradeAndOtherCurrentReceivables": "Trade and other current receivables",
  "ifrs-smes:TradeAndOtherPayables": "Trade and other payables",
  "ifrs-smes:TradeAndOtherPayablesToTradeSuppliers": "Trade payables",
  "ifrs-smes:TradeAndOtherReceivables": "Trade and other receivables",
  "ifrs-smes:TreasuryShares": "Treasury shares",
  "ifrs-smes:Vehicles": "Vehicles",
  "ifrs-smes:WarrantyProvision": "Warranty provision",
  "ifrs-smes:WorkInProgress": "Current work in progress",
  "ssmt-mpers:AdjustmentsForAmortisationExpense": "Adjustments for amortisation",
  "ssmt-mpers:AdjustmentsForDepreciationExpense": "Adjustment for depreciation",
  "ssmt-mpers:AdjustmentsForDividendIncome": "Adjustments for dividend income",
  "ssmt-mpers:AdjustmentsForFinanceIncome": "Adjustments for finance income",
  "ssmt-mpers:AdjustmentsForShareOfProfitOfEquityAccountedAssociatesAndJointVenturesNetOfTax": "Adjustments for share of profit of equity-accounted associates and joint ventures, net of tax",
  "ssmt-mpers:AggregateProfitLoss": "Aggregate Profit (loss)",
  "ssmt-mpers:AggregateProfitLossBeforeTax": "Aggregate profit (loss) before tax",
  "ssmt-mpers:AmortisationExpense": "Amortisation expense",
  "ssmt-mpers:AuditorsRemuneration": "Auditor's remuneration",
  "ssmt-mpers:AuditorsRemunerationForAuditServices": "Auditor's remuneration for audit services",
  "ssmt-mpers:AuditorsRemunerationForOtherServices": "Auditor's remuneration for other services",
  "ssmt-mpers:BenefitsInKindExpenses": "Benefits-in-kind",
  "ssmt-mpers:BonusToDirectors": "Bonus",
  "ssmt-mpers:BuildingOnFreeholdLand": "Building on freehold land",
  "ssmt-mpers:BuildingOnLongtermLeaseholdLand": "Building on long term leasehold land",
  "ssmt-mpers:BuildingOnShorttermLeaseholdLand": "Building on short term leasehold land",
  "ssmt-mpers:CapitalFromNonredeemablePreferenceShares": "Capital from non-redeemable preference shares",
  "ssmt-mpers:CapitalFromOrdinaryShares": "Capital from ordinary shares",
  "ssmt-mpers:CapitalFromRedeemablePreferenceShares": "Capital from redeemable preference shares",
  "ssmt-mpers:CapitalReserve": "Capital reserve",
  "ssmt-mpers:CashEquivalentsWithOtherFinancialInstitutions": "Cash equivalents with other financial institutions",
  "ssmt-mpers:CashFlowsFromUsedInOperations": "Cash generated from (used in) operations",
  "ssmt-mpers:CashSettledShareBasedPaymentLiability": "Cash-settled share-based payment liability",
  "ssmt-mpers:CurrenPortionOfSecuredConvertibleNotes": "Secured convertible notes",
  "ssmt-mpers:CurrentBiologicalAssets": "Current biological assets",
  "ssmt-mpers:CurrentCashSettledShareBasedPaymentLiability": "Current cash-settled share-based payment liability",
  "ssmt-mpers:CurrentDefinedBenefitPlan": "Current defined benefit plan",
  "ssmt-mpers:CurrentDefinedContributionPlan": "Current defined contribution plan",
  "ssmt-mpers:CurrentDerivativeFinancialAssets": "Derivative financial assets",
  "ssmt-mpers:CurrentDerivativeFinancialLiabilities": "Derivative financial liabilities",
  "ssmt-mpers:CurrentEmploymentTerminationBenefits": "Current employment termination benefits",
  "ssmt-mpers:CurrentInvestments": "Other investments",
  "ssmt-mpers:CurrentNontradeAccruals": "Accruals",
  "ssmt-mpers:CurrentNontradeDeferredIncome": "Deferred income",
  "ssmt-mpers:CurrentNontradePayables": "Current non-trade payables",
  "ssmt-mpers:CurrentNontradeRetentionPayable": "Retention payable",
  "ssmt-mpers:CurrentOtherEmployeeBenefitLiabilities": "Other current employee benefit liabilities",
  "ssmt-mpers:CurrentPortionOfFinanceLeaseLiabilities": "Finance lease liabilities",
  "ssmt-mpers:CurrentPortionOfLoanFromHoldingCompany": "Loan from holding company",
  "ssmt-mpers:CurrentPortionOfLoanFromOtherRelatedCompanies": "Loan from other related companies",
  "ssmt-mpers:CurrentPortionOfNoncurrentSecuredBankOverdrafts": "Current portion of non-current secured bank overdrafts",
  "ssmt-mpers:CurrentPortionOfNoncurrentSecuredOtherBankLoanReceived": "Other secured bank loans received",
  "ssmt-mpers:CurrentPortionOfNoncurrentUnsecuredBankOverdrafts": "Unsecured bank overdrafts",
  "ssmt-mpers:CurrentPortionOfNoncurrentUnsecuredOtherBankLoansReceived": "Other unsecured bank loans received",
  "ssmt-mpers:CurrentPortionOfUnsecuredConvertibleNotes": "Unsecured convertible notes",
  "ssmt-mpers:CurrentProvisionForUnconsumedLeave": "Current provision for unconsumed leave",
  "ssmt-mpers:CurrentSecuredBankLoansReceivedAndCurrentPortionOfNoncurrentSecuredBankLoansReceived": "Secured bank loans",
  "ssmt-mpers:CurrentTradePayableDueToContractCustomer": "Current trade payables due to contract suppliers",
  "ssmt-mpers:CurrentTradePayablesDueToAssociates": "Current trade payables due to associates",
  "ssmt-mpers:CurrentTradePayablesDueToHoldingCompany": "Current trade payables due to holding company",
  "ssmt-mpers:CurrentTradePayablesDueToJointVentures": "Current trade payables due to joint ventures",
  "ssmt-mpers:CurrentTradePayablesDueToRelatedCompanies": "Trade payables due to other related parties",
  "ssmt-mpers:CurrentTradePayablesDueToSubsidiaries": "Current trade payables due to subsidiaries",
  "ssmt-mpers:CurrentTradeReceivables": "Current trade receivables",
  "ssmt-mpers:CurrentTradeReceivablesDueFromAssociates": "Current trade receivables due from associates",
  "ssmt-mpers:CurrentTradeReceivablesDueFromContractCustomers": "Current trade receivables due from contract customers",
  "ssmt-mpers:CurrentTradeReceivablesDueFromHoldingCompany": "Current trade receivables due from holding company",
  "ssmt-mpers:CurrentTradeReceivablesDueFromJointVentures": "Current trade receivables due from joint ventures",
  "ssmt-mpers:CurrentTradeReceivablesDueFromRelatedParties": "Current trade receivables due from related parties",
  "ssmt-mpers:CurrentTradeReceivablesDueFromSubsidiaries": "Current trade receivables due from subsidiaries",
  "ssmt-mpers:CurrentUnsecuredBankLoansReceivedAndCurrentPortionOfNoncurrentUnsecuredBankLoansReceived": "Unsecured bank loans",
  "ssmt-mpers:DefinedBenefitPlan": "Defined benefit plan",
  "ssmt-mpers:DefinedContributionPlan": "Defined contribution plan",
  "ssmt-mpers:DepositsAndPlacementsWithLicensedBanks": "Deposits and placements with licensed banks",
  "ssmt-mpers:DepositsPlacedWithOtherCorporations": "Deposit placed with other corporations",
  "ssmt-mpers:DirectorsFees": "Fees",
  "ssmt-mpers:DirectorsRemuneration": "Director's remuneration",
  "ssmt-mpers:DistributableReseves": "Distributable reserves",
  "ssmt-mpers:EmploymentTerminationBenefits": "Employment termination benefits",
  "ssmt-mpers:EquityComponentOfIrredeemableConvertibleUnsecuredLoanStocks": "Equity component of Irredeemable Convertible Unsecured Loan Stocks (ICULS)",
  "ssmt-mpers:EquityComponentOfPreferenceShares": "Equity component of preference shares",
  "ssmt-mpers:EquityComponentsOfOtherFinancialInstruments": "Equity components of other financial instruments",
  "ssmt-mpers:FinishedGoods": "Finished goods",
  "ssmt-mpers:FixedDepositsWithFinancialInstitutions": "Fixed deposits with financial institutions",
  "ssmt-mpers:FreeholdLand": "Freehold land",
  "ssmt-mpers:GainsLossesOnDisposalOfOtherInvestments": "Gains (losses) on disposal of other investments",
  "ssmt-mpers:GainsLossesOnDisposalsOfInvestmentProperties": "Gains (losses) on disposals of investment properties",
  "ssmt-mpers:GainsLossesOnDisposalsOfPropertyPlantAndEquipment": "Gains (losses) on disposals of property, plant and equipment",
  "ssmt-mpers:IncreaseDecreaseInRetainedEarnings": "increase (decrease) in retained earnings",
  "ssmt-mpers:IncreaseDecreaseThroughAcquisitionOfSubsidiary": "Acquisition (dilution) of equity interest in subsidiaries",
  "ssmt-mpers:IncreaseDecreaseThroughConversionOfConvertibleInstruments": "Arising from conversion of Irredeemable Convertible Unsecured Loan Stock (ICULS)",
  "ssmt-mpers:IncreaseDecreaseThroughTransactionsWithOwners": "Other transactions with owners",
  "ssmt-mpers:InvestmentInAssociatesQuotedSharesInMalaysia": "Investment in associates quoted shares in Malaysia",
  "ssmt-mpers:InvestmentInAssociatesQuotedSharesOutsideMalaysia": "Investment in associates quoted shares outside Malaysia",
  "ssmt-mpers:InvestmentInJointVenturesQuotedSharesInMalaysia": "Investment in joint ventures quoted shares in Malaysia",
  "ssmt-mpers:InvestmentInJointVenturesQuotedSharesOutsideMalaysia": "Investment in joint ventures quoted shares outside Malaysia",
  "ssmt-mpers:InvestmentInSubisidiaries": "Investments in subsidiaries",
  "ssmt-mpers:InvestmentInSubsidiariesQuotedSharesInMalaysia": "Investment in subsidiaries quoted shares in Malaysia",
  "ssmt-mpers:InvestmentInSubsidiariesQuotedSharesOutsideMalaysia": "Investment in subsidiaries quoted shares outside Malaysia",
  "ssmt-mpers:InvestmentPropertyBuildingUnderConstruction": "Building under construction",
  "ssmt-mpers:InvestmentPropertyFreeholdLandAndBuilding": "Freehold land and building",
  "ssmt-mpers:InvestmentPropertyLongtermLeaseholdLand": "Investment property long-term leasehold land",
  "ssmt-mpers:InvestmentPropertyShorttermLeaseholdLand": "Investment property short-term leasehold land",
  "ssmt-mpers:InvestmentsInAssociatesOtherInvestmentsNetOfImpairmentLosses": "Other investments in associates, net of impairment losses",
  "ssmt-mpers:InvestmentsInAssociatesShareOfPostAcquisitionProfitsAndReserves": "Share of post-acquisition profits and reserves",
  "ssmt-mpers:InvestmentsInAssociatesUnquotedSharesNetOfImpairmentLosses": "Unquoted shares, net of impairment losses",
  "ssmt-mpers:InvestmentsInJointVentureOtherInvestment": "Other investments in joint ventures",
  "ssmt-mpers:InvestmentsInJointVentureShareOfPostAcquisitionProfitsAndReserves": "Share of post-acquisition profits and reserves",
  "ssmt-mpers:InvestmentsInJointVentureUnquotedSharesNetOfImpairmentLosses": "Unquoted shares, net of impairment losses",
  "ssmt-mpers:InvestmentsInSubsidiariesOtherInvestmentsNetOfImpairmentLosses": "Other investments in subsidiaries, net of impairment losses",
  "ssmt-mpers:InvestmentsInSubsidiariesUnquotedSharesNetOfImpairmentLosses": "Unquoted shares, net of impairment losses",
  "ssmt-mpers:IssueOfConvertibleInstruments": "Issue of convertible notes, net of tax",
  "ssmt-mpers:KeyManagementPersonnelCompensationSharebasedPayment": "Share option expenses",
  "ssmt-mpers:LeasedProperties": "Leased properties",
  "ssmt-mpers:LongtermLeaseholdLand": "Long term leasehold land",
  "ssmt-mpers:LongtermProvisionForDecommissioningRestorationAndRehabilitationCosts": "Provision for decommissioning, restoration and rehabilitation costs",
  "ssmt-mpers:LossOnDisposalOfAssociates": "Loss on disposal of associates",
  "ssmt-mpers:LossOnDisposalOfJointVentures": "Loss on disposal of joint ventures",
  "ssmt-mpers:LossOnDisposalOfSubsidiaries": "Loss on disposal of subsidiaries",
  "ssmt-mpers:LossOnDisposalOfSubsidiariesAssociatesAndJointVentures": "Loss on disposal of subsidiaries, joint ventures and associates",
  "ssmt-mpers:LossOnRevaluationOfFinancialInstruments": "Loss on revaluation",
  "ssmt-mpers:LossesOnDisposalsOfInvestments": "Loss on disposal from other investments",
  "ssmt-mpers:LossesOnDisposalsOfNoncurrentAssets": "Loss on disposal of other non-current assets",
  "ssmt-mpers:LossesOnDisposalsOfPropertyPlantAndEquipment": "Loss on disposal of property, plant and equipment",
  "ssmt-mpers:NaturalDisasterRelatedExpenses": "Natural disaster related expenses",
  "ssmt-mpers:NoncurrentBiologicalAssets": "Non-current biological assets",
  "ssmt-mpers:NoncurrentBorrowings": "Non-current borrowings",
  "ssmt-mpers:NoncurrentInvestmentsOtherThanInvestmentsAccountedForUsingEquityMethod": "Other investments",
  "ssmt-mpers:NoncurrentNontradeAccruals": "Accruals",
  "ssmt-mpers:NoncurrentNontradeDeferredIncome": "Deferred income",
  "ssmt-mpers:NoncurrentNontradePayables": "Non-current non-trade payables",
  "ssmt-mpers:NoncurrentNontradeRetentionPayables": "Retention payable",
  "ssmt-mpers:NoncurrentPortionOfFinanceLeaseLiabilities": "Finance lease liabilities",
  "ssmt-mpers:NoncurrentPortionOfLoanFromHoldingCompany": "Loan from holding company",
  "ssmt-mpers:NoncurrentPortionOfLoanFromOtherRelatedCompanies": "Loan from other related companies",
  "ssmt-mpers:NoncurrentPortionOfNoncurrentSecuredBankLoansReceived": "Secured bank loans",
  "ssmt-mpers:NoncurrentPortionOfNoncurrentUnsecuredBankLoansReceived": "Unsecured bank loans",
  "ssmt-mpers:NoncurrentPortionOfOtherNoncurrentBorrowings": "Other non-current borrowings",
  "ssmt-mpers:NoncurrentPortionOfSecuredConvertibleNotes": "Secured convertible notes",
  "ssmt-mpers:NoncurrentPortionOfUnsecuredConvertibleNotes": "Unsecured convertible notes",
  "ssmt-mpers:NoncurrentTradePayablesDueToAssociates": "Non-current trade payables due to associates",
  "ssmt-mpers:NoncurrentTradePayablesDueToHoldingCompany": "Non-current trade payables due to holding company",
  "ssmt-mpers:NoncurrentTradePayablesDueToJointVentures": "Non-current trade payables due to joint ventures",
  "ssmt-mpers:NoncurrentTradePayablesDueToOtherRelatedParties": "Trade payables due to other related parties",
  "ssmt-mpers:NoncurrentTradePayablesDueToSubsidiaries": "Non-current trade payables due to subsidiaries",
  "ssmt-mpers:NoncurrentTradeReceivables": "Non-current trade receivables",
  "ssmt-mpers:NoncurrentTradeReceivablesDueFromAssociates": "Non-current trade receivables due from associates",
  "ssmt-mpers:NoncurrentTradeReceivablesDueFromHoldingCompany": "Non-current trade receivables due from holding company",
  "ssmt-mpers:NoncurrentTradeReceivablesDueFromJointVentures": "Non-current trade receivables due from joint ventures",
  "ssmt-mpers:NoncurrentTradeReceivablesDueFromRelatedParties": "Non-current trade receivables due from related parties",
  "ssmt-mpers:NoncurrentTradeReceivablesDueFromSubsidiaries": "Non-current trade receivables due from subsidiaries",
  "ssmt-mpers:NondistributableReserves": "Non-distributable other reserves",
  "ssmt-mpers:NontradeDividendReceivables": "Non-trade dividend receivables",
  "ssmt-mpers:NontradeInterestReceivables": "Non-trade interest receivables",
  "ssmt-mpers:NontradeLeaseAndHirePurchaseReceivables": "Non-trade lease and hire purchase receivables",
  "ssmt-mpers:NontradeReceivables": "Non-trade receivables",
  "ssmt-mpers:NontradeReceivablesDeposits": "Non-trade receivables deposits",
  "ssmt-mpers:OfficeEquipmentFixtureAndFittings": "Office equipment, fixture and fittings",
  "ssmt-mpers:OtherAccruedIncome": "Other accrued income",
  "ssmt-mpers:OtherBorrowings": "Other borrowings",
  "ssmt-mpers:OtherBorrowingsFinanceLeaseLiabilities": "Finance lease liabilities",
  "ssmt-mpers:OtherBorrowingsLoanFromAssociates": "Other borrowings loan from associates",
  "ssmt-mpers:OtherBorrowingsLoanFromHoldingCompany": "Loan from holding company",
  "ssmt-mpers:OtherBorrowingsLoanFromJointVentures": "Other borrowings loan from joint venture",
  "ssmt-mpers:OtherBorrowingsLoanFromOtherRelatedCompanies": "Loan from other related companies",
  "ssmt-mpers:OtherBorrowingsLoanFromSubsidiaries": "Other borrowings loan from subsidiaries",
  "ssmt-mpers:OtherBorrowingsRedeemablePreferenceShares": "Other borrowings redeemable preference shares",
  "ssmt-mpers:OtherComponentsOfEquity": "Equity, others components",
  "ssmt-mpers:OtherCurrentAccruedIncome": "Accrued income",
  "ssmt-mpers:OtherCurrentAssets": "Other current assets",
  "ssmt-mpers:OtherCurrentLiabilities": "Other current liabilities",
  "ssmt-mpers:OtherCurrentMiscellaneousNontradeReceivables": "Other current non-trade receivables",
  "ssmt-mpers:OtherCurrentNontradeDeposits": "Deposits",
  "ssmt-mpers:OtherCurrentNontradeDividendReceivables": "Dividend receivables",
  "ssmt-mpers:OtherCurrentNontradeFinanceIncomeReceivable": "Interest receivable",
  "ssmt-mpers:OtherCurrentNontradeLeaseAndHirePurchaseReceivables": "Lease and hire purchase receivables",
  "ssmt-mpers:OtherCurrentNontradePayables": "Other current non-trade payables",
  "ssmt-mpers:OtherCurrentNontradeReceivables": "Non trade receivables",
  "ssmt-mpers:OtherCurrentPayables": "Other current payables",
  "ssmt-mpers:OtherCurrentPayablesDueToAssociates": "Other current payables due to associates",
  "ssmt-mpers:OtherCurrentPayablesDueToHoldingCompany": "Other current payables due to holding company",
  "ssmt-mpers:OtherCurrentPayablesDueToJointVentures": "Other current payables due to joint ventures",
  "ssmt-mpers:OtherCurrentPayablesDueToOtherRelatedParties": "Other current payables due to other related parties",
  "ssmt-mpers:OtherCurrentPayablesDueToRelatedParties": "Current payables due to related parties",
  "ssmt-mpers:OtherCurrentPayablesDueToSubsidiaries": "Other current payables due to subsidiaries",
  "ssmt-mpers:OtherCurrentPortionOfLoanFromAssociates": "Other current portion of loan from associates",
  "ssmt-mpers:OtherCurrentPortionOfLoanFromJointVentures": "Other current portion of loan from joint ventures",
  "ssmt-mpers:OtherCurrentPortionOfLoanFromSubsidiaries": "Other current portion of loan from subsidiaries",
  "ssmt-mpers:OtherCurrentPortionOfMiscellaneousBorrowings": "Other current portion of miscellaneous borrowings",
  "ssmt-mpers:OtherCurrentPortionOfRedeemablePreferenceShares": "Other current portion of redeemable preference shares",
  "ssmt-mpers:OtherCurrentPrepayments": "Prepayments",
  "ssmt-mpers:OtherCurrentPrepaymentsAndCurrentAccruedIncome": "Current prepayments and current accrued income",
  "ssmt-mpers:OtherCurrentReceivables": "Other current receivables",
  "ssmt-mpers:OtherCurrentReceivablesDueFromAssociates": "Other current receivables due from associates",
  "ssmt-mpers:OtherCurrentReceivablesDueFromHoldingCompany": "Other current receivables due from holding company",
  "ssmt-mpers:OtherCurrentReceivablesDueFromJointVentures": "Other current receivables due from joint ventures",
  "ssmt-mpers:OtherCurrentReceivablesDueFromOtherRelatedParties": "Other receivables due from other related parties",
  "ssmt-mpers:OtherCurrentReceivablesDueFromRelatedParties": "Other current receivables due from related parties",
  "ssmt-mpers:OtherCurrentReceivablesDueFromSubsidiaries": "Other current receivables due from subsidiaries",
  "ssmt-mpers:OtherCurrentTradePayables": "Other current trade payables",
  "ssmt-mpers:OtherCurrentTradeReceivables": "Other current trade receivables",
  "ssmt-mpers:OtherDirectorsRemuneration": "Other emoluments",
  "ssmt-mpers:OtherDistributableReserve": "Other distributable reserves",
  "ssmt-mpers:OtherEmployeeBenefitLiabilities": "Other employee benefit",
  "ssmt-mpers:OtherInventories": "Other inventories",
  "ssmt-mpers:OtherInvestmentProperty": "Other investment property",
  "ssmt-mpers:OtherMiscellaneousExpenses": "Other miscellaneous expenses",
  "ssmt-mpers:OtherMiscellaneousNontradePayables": "Other miscellaneous non-trade payables",
  "ssmt-mpers:OtherNoncurrentAssets": "Other non-current assets",
  "ssmt-mpers:OtherNoncurrentLiabilities": "Other non-current liabilities",
  "ssmt-mpers:OtherNoncurrentNontradeLeaseAndHirePurchaseReceivables": "Lease and hire purchase receivables",
  "ssmt-mpers:OtherNoncurrentNontradeMiscellaneous": "Miscellaneous other non-current non-trade receivables",
  "ssmt-mpers:OtherNoncurrentNontradePayables": "Other non-current non-trade payables",
  "ssmt-mpers:OtherNoncurrentNontradePrepaymentAndAccruedIncome": "Prepayment and accrued income",
  "ssmt-mpers:OtherNoncurrentNontradeReceivables": "Other non-current non-trade receivables",
  "ssmt-mpers:OtherNoncurrentPayables": "Other non-current payables",
  "ssmt-mpers:OtherNoncurrentPayablesDueToRelatedCompanies": "Other payables due to related parties",
  "ssmt-mpers:OtherNoncurrentPayablesDueToRelatedParties": "Non-current other payables due to related parties",
  "ssmt-mpers:OtherNoncurrentPortionOfLoanFromAssociates": "Other non-current portion of loan from associates",
  "ssmt-mpers:OtherNoncurrentPortionOfLoanFromJointVentures": "Other non-current portion of loan from joint ventures",
  "ssmt-mpers:OtherNoncurrentPortionOfLoanFromSubsidiaries": "Other non-current portion of loan from subsidiaries",
  "ssmt-mpers:OtherNoncurrentPortionOfRedeemablePreferenceShares": "Other non-current portion of redeemable preference shares",
  "ssmt-mpers:OtherNoncurrentReceivables": "Other non-current receivables",
  "ssmt-mpers:OtherNoncurrentReceivablesDueFromAssociates": "Other non-current receivables due from associates",
  "ssmt-mpers:OtherNoncurrentReceivablesDueFromHoldingCompany": "Other non-current receivables due from holding company",
  "ssmt-mpers:OtherNoncurrentReceivablesDueFromJointVentures": "Other non-current receivables due from joint ventures",
  "ssmt-mpers:OtherNoncurrentReceivablesDueFromOtherRelatedParties": "Other non-current receivables due from other related parties",
  "ssmt-mpers:OtherNoncurrentReceivablesDueFromRelatedParties": "Other non-current receivables due from related parties",
  "ssmt-mpers:OtherNoncurrentReceivablesDueFromSubsidiaries": "Other non-current receivables due from subsidiaries",
  "ssmt-mpers:OtherNoncurrentSecuredBankLoans": "Other non-current secured bank loans",
  "ssmt-mpers:OtherNoncurrentTradePayables": "Other non-current trade payables",
  "ssmt-mpers:OtherNoncurrentTradePayablesDueToAssociates": "Other non-current trade payables due to associates",
  "ssmt-mpers:OtherNoncurrentTradePayablesDueToHoldingCompany": "Other non-current trade payables due to holding company",
  "ssmt-mpers:OtherNoncurrentTradePayablesDueToJointVentures": "Other non-current trade payables due to joint ventures",
  "ssmt-mpers:OtherNoncurrentTradePayablesDueToSubsidiaries": "Other non-current trade payables due to subsidiaries",
  "ssmt-mpers:OtherNoncurrentTradeReceivables": "Other non-current trade receivables",
  "ssmt-mpers:OtherNoncurrentUnsecuredBankLoans": "Other non-current unsecured bank loans",
  "ssmt-mpers:OtherNondistributableReserves": "Other non-distributable reserves",
  "ssmt-mpers:OtherNontradeAccruals": "Other non-trade accruals",
  "ssmt-mpers:OtherNontradeDeferredIncome": "Other non-trade deferred income",
  "ssmt-mpers:OtherNontradePayables": "Other non-trade payables",
  "ssmt-mpers:OtherNontradeReceivables": "Other non-trade receivables",
  "ssmt-mpers:OtherNontradeRetentionPayables": "Other non-trade retention payables",
  "ssmt-mpers:OtherPayables": "Other payables",
  "ssmt-mpers:OtherPayablesDueToAssociates": "Other payables due to associates",
  "ssmt-mpers:OtherPayablesDueToHoldingCompany": "Other payables due to holding company",
  "ssmt-mpers:OtherPayablesDueToJointVentures": "Other payables due to joint ventures",
  "ssmt-mpers:OtherPayablesDueToOtherRelatedParties": "Other payables due to other related parties",
  "ssmt-mpers:OtherPayablesDueToRelatedParties": "Other payables due to related parties",
  "ssmt-mpers:OtherPayablesDueToSubsidiaries": "Other payables due to subsidiaries",
  "ssmt-mpers:OtherPrepayments": "Other prepayments",
  "ssmt-mpers:OtherReceivables": "Other receivables",
  "ssmt-mpers:OtherReceivablesDueFromAssociates": "Other receivables due from associates",
  "ssmt-mpers:OtherReceivablesDueFromHoldingCompany": "Other receivables due from holding company",
  "ssmt-mpers:OtherReceivablesDueFromJointVentures": "Other receivables due from joint ventures",
  "ssmt-mpers:OtherReceivablesDueFromOtherRelatedParties": "Other receivables due from other related parties",
  "ssmt-mpers:OtherReceivablesDueFromRelatedParties": "Other receivables due from related parties",
  "ssmt-mpers:OtherReceivablesDueFromSubsidiaries": "Other receivables due from subsidiaries",
  "ssmt-mpers:OtherSecuredBankLoansReceived": "Other secured bank loans received",
  "ssmt-mpers:OtherTradePayables": "Other trade payables",
  "ssmt-mpers:OtherTradeReceivables": "Other trade receivables",
  "ssmt-mpers:PerformanceIncentives": "Performance incentives",
  "ssmt-mpers:PerpetualSukuk": "Perpetual Sukuk",
  "ssmt-mpers:PlantAndEquipment": "Plant and equipment",
  "ssmt-mpers:PrepaymentsAndAccruedIncome": "Prepayments and accrued income",
  "ssmt-mpers:ProfitLossAttributableToOtherComponentsOfEquity": "Profit (loss) attributable to other components of equity",
  "ssmt-mpers:ProvisionForDecommissioningRestorationAndRehabilitationCosts": "Provisions for decommissioning, restoration and rehabilitation costs",
  "ssmt-mpers:ProvisionForGuaranteeAndWarranties": "Provision of warranties and guarantees",
  "ssmt-mpers:ProvisionForLiabilitiesAndCharges": "Provision for liabilities and charges",
  "ssmt-mpers:ProvisionForUnconsumedLeave": "Provision for unconsumed leave",
  "ssmt-mpers:RawMaterials": "Raw materials",
  "ssmt-mpers:ReceivablesFromContractsWithCustomers": "Trade receivables due from contract customers",
  "ssmt-mpers:RentalExpense": "Rental expenses",
  "ssmt-mpers:RepaymentOfLoanFromAssociate": "Repayment of loan from associate",
  "ssmt-mpers:RetirementBenefitsDefinedBenefitPlans": "Retirement benefits - defined benefit plans",
  "ssmt-mpers:RetirementBenefitsDefinedContributionPlans": "Retirement benefits - defined contribution plans",
  "ssmt-mpers:RoyaltyExpense": "Royalty expenses",
  "ssmt-mpers:SecuredBankLoansReceived": "Secured bank loans received",
  "ssmt-mpers:SecuredBankOverdrafts": "Secured bank overdrafts",
  "ssmt-mpers:SecuredConvertibleNotes": "Secured convertible notes",
  "ssmt-mpers:ShorttermLeaseholdLand": "Short term leasehold land",
  "ssmt-mpers:ShorttermProvisionForDecommissioningRestorationAndRehabilitationCosts": "Provision for decommissioning, restoration and rehabilitation costs",
  "ssmt-mpers:SpareParts": "Spare parts",
  "ssmt-mpers:TradePayablesDueToAssociates": "Trade payables due to associate companies",
  "ssmt-mpers:TradePayablesDueToContractCustomers": "Trade payable due to contract suppliers",
  "ssmt-mpers:TradePayablesDueToHoldingCompany": "Trade payables due to holding company",
  "ssmt-mpers:TradePayablesDueToJointVentures": "Trade payables due to joint venture companies",
  "ssmt-mpers:TradePayablesDueToOtherRelatedParties": "Trade payables due to other related parties",
  "ssmt-mpers:TradePayablesDueToSubsidiaries": "Trade payables due to subsidiary companies",
  "ssmt-mpers:TradeReceivables": "Trade receivables",
  "ssmt-mpers:TradeReceivablesDueFromAssociates": "Trade receivables from associates",
  "ssmt-mpers:TradeReceivablesDueFromHoldingCompany": "Trade receivables due from holding company",
  "ssmt-mpers:TradeReceivablesDueFromJointVentures": "Trade receivables due from joint ventures",
  "ssmt-mpers:TradeReceivablesDueFromOtherRelatedParties": "Trade receivables due from other related parties",
  "ssmt-mpers:TradeReceivablesDueFromSubsidiaries": "Trade receivables due from subsidiaries",
  "ssmt-mpers:UnsecuredBankLoansReceived": "Unsecured bank loans received",
  "ssmt-mpers:UnsecuredBankOverdrafts": "Unsecured bank overdrafts",
  "ssmt-mpers:UnsecuredConvertibleNotes": "Unsecured convertible notes",
  "ssmt-mpers:WagesAndSalariesToDirectors": "Salaries and other emoluments",
  "ssmt:CashAndBankBalances": "Cash and bank balances",
  "ssmt:OtherAdjustmentsToReconcileCashAndCashEquivalents": "Other adjustments to reconcile cash and cash equivalents",
};
