// AUTO-DERIVED alongside mbrs-template.ts — regenerate with the same script.
//
// Split out of the template deliberately: the canonical model needs this list
// and is imported by the review page, so keeping it here stops the ~120KB fact
// template from being pulled into the client bundle.

/** XBRL concepts that carry company narrative prose (…Explanatory). */
export const NARRATIVE_CONCEPTS: string[] = [
  "ssmt:DisclosureOfDirectorsReportExplanatory",
  "ssmt:DisclosureOfStatementByDirectorsExplanatory",
  "ssmt:DisclosureOfAuditorsReportToMembersExplanatory",
  "ssmt-mpers:DisclosureOfCorporateInformationExplanatory",
  "ssmt:DisclosureOfSignificantAccountingPoliciesExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForDeferredIncomeTaxExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForEquityInstrumentsExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForOtherFinancialLiabilitiesExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForImpairmentOfNonfinancialAssetsExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForPropertyPlantAndEquipmentExplanatory",
  "ifrs-smes:DescriptionOfAccountingPolicyForRecognitionOfRevenue",
  "ssmt-mpers:DisclosureOfBasisOfPreparationOfFinancialStatementsExplanatory",
  "ssmt-mpers:DisclosureOfCashAndCashEquivalentsExplanatory",
  "ifrs-smes:DisclosureOfChangesInAccountingPoliciesAccountingEstimatesAndErrorsExplanatory",
  "ssmt-mpers:DisclosureOfFinancialInstrumentsExplanatory",
  "ifrs-smes:DisclosureOfGeneralInformationAboutFinancialStatementsExplanatory",
  "ifrs-smes:DisclosureOfIncomeTaxExplanatory",
  "ssmt-mpers:DisclosureOfOtherNotesToAccountsExplanatory",
  "ssmt-mpers:DisclosureOfProfitAfterTaxExplanatory",
  "ifrs-smes:DisclosureOfPropertyPlantAndEquipmentExplanatory",
  "ifrs-smes:DisclosureOfRevenueExplanatory",
  "ifrs-smes:DisclosureOfShareCapitalReservesAndOtherEquityInterestExplanatory",
  "ssmt-mpers:DisclosureOfTradeAndOtherPayablesExplanatory",
  "ssmt-mpers:DisclosureOfTradeAndOtherReceivablesExplanatory",
  "ifrs-smes:DisclosureOfClassesOfShareCapitalExplanatory",
  "ifrs-smes:DisclosureOfTransactionsBetweenRelatedPartiesExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForBorrowingCostsExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForCashFlowsExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForIncomeTaxExplanatory",
  "ifrs-smes:DescriptionOfAccountingPolicyForInvestmentInAssociates",
  "ssmt-mpers:DescriptionOfAccountingPolicyForInvestmentPropertyExplanatory",
  "ssmt-mpers:DisclosureOfAuthorisationOfFinancialStatementsExplanatory",
  "ssmt-mpers:DisclosureOfBorrowingsExplanatory",
  "ssmt-mpers:DisclosureOfDeferredTaxesExplanatory",
  "ssmt-mpers:DisclosureOfFinanceCostExplanatory",
  "ifrs-smes:DisclosureOfInvestmentPropertyExplanatory",
  "ssmt-mpers:DisclosureOfInvestmentInAssociateExplanatory",
  "ssmt-mpers:DisclosureOfOtherIncomeExplanatory",
  "ssmt-mpers:DisclosureOfOtherInvestmentsExplanatory",
  "ifrs-smes:DescriptionOfAccountingPolicyForInvestmentsInJointVentures",
  "ifrs-smes:DescriptionOfAccountingPolicyForMeasuringInventories",
  "ifrs-smes:DisclosureOfEffectOfChangesInForeignExchangeRatesExplanatory",
  "ifrs-smes:DisclosureOfFirstTimeAdoptionExplanatory",
  "ifrs-smes:DisclosureOfInventoriesExplanatory",
  "ifrs-smes:DisclosureOfLeasesExplanatory",
  "ifrs-smes:DisclosureOfSharebasedPaymentArrangementsExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForAmortisationExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForBasisOfConsolidationExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForBasisOfPresentationOfFinancialStatementsExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForBiologicalAssetsExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForBorrowingsExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForBusinessCombinationsExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForCollateralExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForConstructionContractExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForContingentAssetsExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForContingentLiabilitiesExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForDecommissioningRestorationAndRehabilitationProvisionsExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForDepreciationExpenseExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForDividendsExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForEarningsPerShareExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForEmployeeBenefitsExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForFeeAndCommissionIncomeAndExpenseExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForForeignCurrencyTranslationExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForFunctionalAndPresentationCurrencyExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForGoodsSoldExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForGoodwillExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForGovernmentGrantsExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForIntangibleAssetsOtherThanGoodwillExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForInterestIncomeAndExpenseExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForInvestmentInSubsidiariesExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForIssueExpensesExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForLeasesExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForNoncurrentAssetsOrDisposalGroupsClassifiedAsHeldForSaleExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForOnerousContractsExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForOtherSignificantAccountingPoliciesRelevantToUnderstandingOfFinancialStatementsExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForPreferenceShareCapitalExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForProvisionsExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForRentalIncomeExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForRestructuringExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForSegmentReportingExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForStatePlansExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForTransactionsWithRelatedPartiesExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForWarrantiesExplanatory",
  "ssmt-mpers:DisclosureOfAcquisitionsAndDisposalsExplanatory",
  "ssmt-mpers:DisclosureOfAuditorsRemunerationExplanatory",
  "ssmt-mpers:DisclosureOfBiologicalAssetsAndGovernmentGrantsForAgriculturalActivityExplanatory",
  "ssmt-mpers:DisclosureOfCapitalAndReserveExplanatory",
  "ssmt-mpers:DisclosureOfClaimsAndBenefitsPaidExplanatory",
  "ssmt-mpers:DisclosureOfCollateralExplanatory",
  "ssmt-mpers:DisclosureOfCommitmentsExplanatory",
  "ssmt-mpers:DisclosureOfContingentAssetsAndContingentLiabilitiesExplanatory",
  "ssmt-mpers:DisclosureOfConvertibleNotesExplanatory",
  "ssmt-mpers:DisclosureOfCostOfSalesExplanatory",
  "ssmt-mpers:DisclosureOfCreditRiskExplanatory",
  "ssmt-mpers:DisclosureOfCurrentTaxAssetsAndCurrentTaxLiabilitiesExplanatory",
  "ssmt-mpers:DisclosureOfDeferredIncomeExplanatory",
  "ssmt-mpers:DisclosureOfDepositsFromBanksExplanatory",
  "ssmt-mpers:DisclosureOfDepreciationAndAmortisationExpenseExplanatory",
  "ssmt-mpers:DisclosureOfDerivativeFinancialInstrumentsExplanatory",
  "ssmt-mpers:DisclosureOfDiscontinuedOperationsExplanatory",
  "ssmt-mpers:DisclosureOfDividendsExplanatory",
  "ssmt-mpers:DisclosureOfEarningsPerShareExplanatory",
  "ssmt-mpers:DisclosureOfEmploymentTerminationBenefitsExplanatory",
  "ssmt-mpers:DisclosureOfEntitysReportableSegmentsExplanatory",
  "ssmt-mpers:DisclosureOfExplanationOfTransitionToMPERSExplanatory",
  "ssmt-mpers:DisclosureOfFeeAndCommissionIncomeExpenseExplanatory",
  "ssmt-mpers:DisclosureOfFinanceIncomeExplanatory",
  "ssmt-mpers:DisclosureOfFinancialInstrumentsAtFairValueThroughProfitOrLossExplanatory",
  "ssmt-mpers:DisclosureOfFinancialInstrumentsMeasuredAtAmortisedCostExplanatory",
  "ssmt-mpers:DisclosureOfForeignCurrencyTranslationReserveExplanatory",
  "ssmt-mpers:DisclosureOfGoingConcernExplanatory",
  "ssmt-mpers:DisclosureOfGrantsAndContributionsExplanatory",
  "ssmt-mpers:DisclosureOfHedgingActivityExplanatory",
  "ssmt-mpers:DisclosureOfImpairmentOfAssetsExplanatory",
  "ssmt-mpers:DisclosureOfIntangibleAssetsAndGoodwillExplanatory",
  "ssmt-mpers:DisclosureOfInterestExpenseExplanatory",
  "ssmt-mpers:DisclosureOfInterestInAssociatesJointVenturesOrJointlyControlledOperationExplanatory",
  "ssmt-mpers:DisclosureOfInterestIncomeExplanatory",
  "ssmt-mpers:DisclosureOfInvestmentInJointlyControlledExplanatory",
  "ssmt-mpers:DisclosureOfInvestmentInSubsidiaryCompaniesExplanatory",
  "ssmt-mpers:DisclosureOfLiquidityRiskExplanatory",
  "ssmt-mpers:DisclosureOfLoansAndAdvancesToBanksExplanatory",
  "ssmt-mpers:DisclosureOfMarketRiskExplanatory",
  "ssmt-mpers:DisclosureOfNonAdjustingEventsAfterEndOfReportingPeriodExplanatory",
  "ssmt-mpers:DisclosureOfNoncontrollingInterestsExplanatory",
  "ssmt-mpers:DisclosureOfNoncurrentAssetsHeldForSaleAndDiscontinuedOperationsExplanatory",
  "ssmt-mpers:DisclosureOfOtherComprehensiveIncomeExplanatory",
  "ssmt-mpers:DisclosureOfOtherCurrentAssetsExplanatory",
  "ssmt-mpers:DisclosureOfOtherCurrentLiabilitiesExplanatory",
  "ssmt-mpers:DisclosureOfOtherLongTermEmploymentBenefitsExplanatory",
  "ssmt-mpers:DisclosureOfOtherNoncurrentAssetsExplanatory",
  "ssmt-mpers:DisclosureOfOtherNoncurrentLiabilitiesExplanatory",
  "ssmt-mpers:DisclosureOfOtherOperatingExpenseExplanatory",
  "ssmt-mpers:DisclosureOfOtherReservesExplanatory",
  "ssmt-mpers:DisclosureOfPerpetualSukukExplanatory",
  "ssmt-mpers:DisclosureOfPostEmploymentBenefitObligationsExplanatory",
  "ssmt-mpers:DisclosureOfProvisionsExplanatory",
  "ssmt-mpers:DisclosureOfRedeemablePreferenceSharesExplanatory",
  "ssmt-mpers:DisclosureOfServiceConcessionArrangementsExplanatory",
  "ssmt-mpers:DisclosureOfSubsequentEventsExplanatory",
  "ssmt-mpers:ExplanationOfReasonsForReclassificationOfPreviousFinancialStatementsFiguresExplanatory",
  "ssmt-mpers:ExplanationOfReasonsForRestatementOfPreviousFinancialStatementsFiguresExplanatory",
  "ssmt-mpers:ExplanationOfReasonsForUsingLongerOrShorterReportingPeriodExplanatory",
];

/** SSM's own label for each narrative concept — given to the model so it
 *  knows which section of the report each key means. */
/** The sections real filings used — every mandatory text block among
 *  them. The main extraction pass asks only for these; the dedicated
 *  narrative pass asks for the full list. */
export const NARRATIVE_CORE: string[] = [
  "ssmt:DisclosureOfDirectorsReportExplanatory",
  "ssmt:DisclosureOfStatementByDirectorsExplanatory",
  "ssmt:DisclosureOfAuditorsReportToMembersExplanatory",
  "ssmt-mpers:DisclosureOfCorporateInformationExplanatory",
  "ssmt:DisclosureOfSignificantAccountingPoliciesExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForDeferredIncomeTaxExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForEquityInstrumentsExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForOtherFinancialLiabilitiesExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForImpairmentOfNonfinancialAssetsExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForPropertyPlantAndEquipmentExplanatory",
  "ifrs-smes:DescriptionOfAccountingPolicyForRecognitionOfRevenue",
  "ssmt-mpers:DisclosureOfBasisOfPreparationOfFinancialStatementsExplanatory",
  "ssmt-mpers:DisclosureOfCashAndCashEquivalentsExplanatory",
  "ifrs-smes:DisclosureOfChangesInAccountingPoliciesAccountingEstimatesAndErrorsExplanatory",
  "ssmt-mpers:DisclosureOfFinancialInstrumentsExplanatory",
  "ifrs-smes:DisclosureOfGeneralInformationAboutFinancialStatementsExplanatory",
  "ifrs-smes:DisclosureOfIncomeTaxExplanatory",
  "ssmt-mpers:DisclosureOfOtherNotesToAccountsExplanatory",
  "ssmt-mpers:DisclosureOfProfitAfterTaxExplanatory",
  "ifrs-smes:DisclosureOfPropertyPlantAndEquipmentExplanatory",
  "ifrs-smes:DisclosureOfRevenueExplanatory",
  "ifrs-smes:DisclosureOfShareCapitalReservesAndOtherEquityInterestExplanatory",
  "ssmt-mpers:DisclosureOfTradeAndOtherPayablesExplanatory",
  "ssmt-mpers:DisclosureOfTradeAndOtherReceivablesExplanatory",
  "ifrs-smes:DisclosureOfClassesOfShareCapitalExplanatory",
  "ifrs-smes:DisclosureOfTransactionsBetweenRelatedPartiesExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForBorrowingCostsExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForCashFlowsExplanatory",
  "ssmt-mpers:DescriptionOfAccountingPolicyForIncomeTaxExplanatory",
  "ifrs-smes:DescriptionOfAccountingPolicyForInvestmentInAssociates",
  "ssmt-mpers:DescriptionOfAccountingPolicyForInvestmentPropertyExplanatory",
  "ssmt-mpers:DisclosureOfAuthorisationOfFinancialStatementsExplanatory",
  "ssmt-mpers:DisclosureOfBorrowingsExplanatory",
  "ssmt-mpers:DisclosureOfDeferredTaxesExplanatory",
  "ssmt-mpers:DisclosureOfFinanceCostExplanatory",
  "ifrs-smes:DisclosureOfInvestmentPropertyExplanatory",
  "ssmt-mpers:DisclosureOfInvestmentInAssociateExplanatory",
  "ssmt-mpers:DisclosureOfOtherIncomeExplanatory",
  "ssmt-mpers:DisclosureOfOtherInvestmentsExplanatory",
];

export const NARRATIVE_LABELS: Record<string, string> = {
  "ssmt:DisclosureOfDirectorsReportExplanatory": "Disclosure of Director's Report [text block]",
  "ssmt:DisclosureOfStatementByDirectorsExplanatory": "Disclosure of Statement by Directors [text block]",
  "ssmt:DisclosureOfAuditorsReportToMembersExplanatory": "Disclosure of auditor's report to members [text block]",
  "ssmt-mpers:DisclosureOfCorporateInformationExplanatory": "Disclosure of corporate information [textblock]",
  "ssmt:DisclosureOfSignificantAccountingPoliciesExplanatory": "Disclosure of significant accounting policies [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForDeferredIncomeTaxExplanatory": "Description of accounting policy for deferred income tax [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForEquityInstrumentsExplanatory": "Description of accounting policy for equity instruments [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForOtherFinancialLiabilitiesExplanatory": "Description of accounting policy for other financial liabilities [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForImpairmentOfNonfinancialAssetsExplanatory": "Description of accounting policy for impairment of non-financial assets [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForPropertyPlantAndEquipmentExplanatory": "Description of accounting policy for property, plant and equipment [text block]",
  "ifrs-smes:DescriptionOfAccountingPolicyForRecognitionOfRevenue": "Description of accounting policy for recognition of revenue [text block]",
  "ssmt-mpers:DisclosureOfBasisOfPreparationOfFinancialStatementsExplanatory": "Disclosure of basis of preparation of financial statements [text block]",
  "ssmt-mpers:DisclosureOfCashAndCashEquivalentsExplanatory": "Disclosure of cash and cash equivalents [text block]",
  "ifrs-smes:DisclosureOfChangesInAccountingPoliciesAccountingEstimatesAndErrorsExplanatory": "Disclosure of changes in accounting policies, accounting estimates and errors [text block]",
  "ssmt-mpers:DisclosureOfFinancialInstrumentsExplanatory": "Disclosure of financial instruments [text block]",
  "ifrs-smes:DisclosureOfGeneralInformationAboutFinancialStatementsExplanatory": "Disclosure of general information about financial statements [text block]",
  "ifrs-smes:DisclosureOfIncomeTaxExplanatory": "Disclosure of income tax [text block]",
  "ssmt-mpers:DisclosureOfOtherNotesToAccountsExplanatory": "Disclosure of other notes to accounts [text block]",
  "ssmt-mpers:DisclosureOfProfitAfterTaxExplanatory": "Disclosure of profit after tax [text block]",
  "ifrs-smes:DisclosureOfPropertyPlantAndEquipmentExplanatory": "Disclosure of property, plant and equipment and investment property at cost less accumulated depreciation and impairment [text block]",
  "ifrs-smes:DisclosureOfRevenueExplanatory": "Disclosure of revenue [text block]",
  "ifrs-smes:DisclosureOfShareCapitalReservesAndOtherEquityInterestExplanatory": "Disclosure of share capital, reserves and other equity interest [text block]",
  "ssmt-mpers:DisclosureOfTradeAndOtherPayablesExplanatory": "Disclosure of trade and other payables [text block]",
  "ssmt-mpers:DisclosureOfTradeAndOtherReceivablesExplanatory": "Disclosure of trade and other receivables [text block]",
  "ifrs-smes:DisclosureOfClassesOfShareCapitalExplanatory": "Disclosure of classes of share capital [text block]",
  "ifrs-smes:DisclosureOfTransactionsBetweenRelatedPartiesExplanatory": "Disclosure of transactions between related parties [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForBorrowingCostsExplanatory": "Description of accounting policy for borrowing costs [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForCashFlowsExplanatory": "Description of accounting policy for cash and cash equivalents [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForIncomeTaxExplanatory": "Description of accounting policy for income tax [text block]",
  "ifrs-smes:DescriptionOfAccountingPolicyForInvestmentInAssociates": "Description of accounting policy for investment in associates [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForInvestmentPropertyExplanatory": "Description of accounting policy for investment property [text block]",
  "ssmt-mpers:DisclosureOfAuthorisationOfFinancialStatementsExplanatory": "Disclosure of authorisation of financial statements [text block]",
  "ssmt-mpers:DisclosureOfBorrowingsExplanatory": "Disclosure of borrowings [text block]",
  "ssmt-mpers:DisclosureOfDeferredTaxesExplanatory": "Disclosure of deferred tax assets/(liabilities) [text block]",
  "ssmt-mpers:DisclosureOfFinanceCostExplanatory": "Disclosure of finance costs [text block]",
  "ifrs-smes:DisclosureOfInvestmentPropertyExplanatory": "Disclosure of investment property at fair value through profit or loss [text block]",
  "ssmt-mpers:DisclosureOfInvestmentInAssociateExplanatory": "Disclosure of investment in associates [text block]",
  "ssmt-mpers:DisclosureOfOtherIncomeExplanatory": "Disclosure of other income [text block]",
  "ssmt-mpers:DisclosureOfOtherInvestmentsExplanatory": "Disclosure of other investments [text block]",
  "ifrs-smes:DescriptionOfAccountingPolicyForInvestmentsInJointVentures": "Description of accounting policy for investments in joint ventures [text block]",
  "ifrs-smes:DescriptionOfAccountingPolicyForMeasuringInventories": "Description of accounting policy for measuring inventories [text block]",
  "ifrs-smes:DisclosureOfEffectOfChangesInForeignExchangeRatesExplanatory": "Disclosure of effect of changes in foreign exchange rates [text block]",
  "ifrs-smes:DisclosureOfFirstTimeAdoptionExplanatory": "Disclosure of first-time adoption [text block]",
  "ifrs-smes:DisclosureOfInventoriesExplanatory": "Disclosure of inventories [text block]",
  "ifrs-smes:DisclosureOfLeasesExplanatory": "Disclosure of leases [text block]",
  "ifrs-smes:DisclosureOfSharebasedPaymentArrangementsExplanatory": "Disclosure of share-based payment arrangements [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForAmortisationExplanatory": "Description of accounting policy for amortisation [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForBasisOfConsolidationExplanatory": "Description of accounting policy for basis of consolidation [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForBasisOfPresentationOfFinancialStatementsExplanatory": "Description of accounting policy for basis of preparation of financial statements [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForBiologicalAssetsExplanatory": "Description of accounting policy for biological assets [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForBorrowingsExplanatory": "Description of accounting policy for borrowings [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForBusinessCombinationsExplanatory": "Description of accounting policy for business combinations [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForCollateralExplanatory": "Description of accounting policy for collateral [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForConstructionContractExplanatory": "Description of accounting policy for construction contracts [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForContingentAssetsExplanatory": "Description of accounting policy for contingent assets [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForContingentLiabilitiesExplanatory": "Description of accounting policy for contingent liabilities [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForDecommissioningRestorationAndRehabilitationProvisionsExplanatory": "Description of accounting policy for decommissioning, restoration and rehabilitation provisions [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForDepreciationExpenseExplanatory": "Description of accounting policy for depreciation expense [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForDividendsExplanatory": "Description of accounting policy for dividend income [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForEarningsPerShareExplanatory": "Description of accounting policy for earnings per share [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForEmployeeBenefitsExplanatory": "Description of accounting policy for employee benefits [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForFeeAndCommissionIncomeAndExpenseExplanatory": "Description of accounting policy for fee and commission income and expense [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForForeignCurrencyTranslationExplanatory": "Description of accounting policy for foreign currency [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForFunctionalAndPresentationCurrencyExplanatory": "Description of accounting policy for functional and presentation currency [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForGoodsSoldExplanatory": "Description of accounting policy for goods sold [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForGoodwillExplanatory": "Description of accounting policy for goodwill [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForGovernmentGrantsExplanatory": "Description of accounting policy for government grants [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForIntangibleAssetsOtherThanGoodwillExplanatory": "Description of accounting policy for intangible assets [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForInterestIncomeAndExpenseExplanatory": "Description of accounting policy for interest income and expense [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForInvestmentInSubsidiariesExplanatory": "Description of accounting policy for investments in subsidiaries [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForIssueExpensesExplanatory": "Description of accounting policy for issue expenses [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForLeasesExplanatory": "Description of accounting policy for leases [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForNoncurrentAssetsOrDisposalGroupsClassifiedAsHeldForSaleExplanatory": "Description of accounting policy for non-current assets or disposal groups classified as held for sale and discontinued operations [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForOnerousContractsExplanatory": "Description of accounting policy for onerous contracts [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForOtherSignificantAccountingPoliciesRelevantToUnderstandingOfFinancialStatementsExplanatory": "Description of other significant accounting policies relevant to understanding of financial statements [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForPreferenceShareCapitalExplanatory": "Description of accounting policy for preference share capital [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForProvisionsExplanatory": "Description of accounting policy for provisions [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForRentalIncomeExplanatory": "Description of accounting policy for rental income [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForRestructuringExplanatory": "Description of accounting policy for restructuring [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForSegmentReportingExplanatory": "Description of accounting policy for segment reporting [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForStatePlansExplanatory": "Description of accounting policy for state plans [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForTransactionsWithRelatedPartiesExplanatory": "Description of accounting policy for transactions with related parties [text block]",
  "ssmt-mpers:DescriptionOfAccountingPolicyForWarrantiesExplanatory": "Description of accounting policy for warranties [text block]",
  "ssmt-mpers:DisclosureOfAcquisitionsAndDisposalsExplanatory": "Disclosure of acquisitions and disposals [text block]",
  "ssmt-mpers:DisclosureOfAuditorsRemunerationExplanatory": "Disclosure of auditors' remuneration [text block]",
  "ssmt-mpers:DisclosureOfBiologicalAssetsAndGovernmentGrantsForAgriculturalActivityExplanatory": "Disclosure of biological assets [text block]",
  "ssmt-mpers:DisclosureOfCapitalAndReserveExplanatory": "Disclosure of capital and reserves [text block]",
  "ssmt-mpers:DisclosureOfClaimsAndBenefitsPaidExplanatory": "Disclosure of claims and benefits paid [text block]",
  "ssmt-mpers:DisclosureOfCollateralExplanatory": "Disclosure of collateral [text block]",
  "ssmt-mpers:DisclosureOfCommitmentsExplanatory": "Disclosure of commitments [text block]",
  "ssmt-mpers:DisclosureOfContingentAssetsAndContingentLiabilitiesExplanatory": "Disclosure of contingent assets and contingent liabilities [text block]",
  "ssmt-mpers:DisclosureOfConvertibleNotesExplanatory": "Disclosure of convertible notes [text block]",
  "ssmt-mpers:DisclosureOfCostOfSalesExplanatory": "Disclosure of cost of sales [text block]",
  "ssmt-mpers:DisclosureOfCreditRiskExplanatory": "Disclosure of credit risk [text block]",
  "ssmt-mpers:DisclosureOfCurrentTaxAssetsAndCurrentTaxLiabilitiesExplanatory": "Disclosure of current tax assets or current tax liabilities [text block]",
  "ssmt-mpers:DisclosureOfDeferredIncomeExplanatory": "Disclosure of deferred income [text block]",
  "ssmt-mpers:DisclosureOfDepositsFromBanksExplanatory": "Disclosure of deposits from banks [text block]",
  "ssmt-mpers:DisclosureOfDepreciationAndAmortisationExpenseExplanatory": "Disclosure of depreciation and amortisation expense [text block]",
  "ssmt-mpers:DisclosureOfDerivativeFinancialInstrumentsExplanatory": "Disclosure of derivative financial instruments [text block]",
  "ssmt-mpers:DisclosureOfDiscontinuedOperationsExplanatory": "Disclosure of discontinued operations [text block]",
  "ssmt-mpers:DisclosureOfDividendsExplanatory": "Disclosure of dividends [text block]",
  "ssmt-mpers:DisclosureOfEarningsPerShareExplanatory": "Disclosure of earnings/loss per share [text block]",
  "ssmt-mpers:DisclosureOfEmploymentTerminationBenefitsExplanatory": "Disclosure of employment termination benefits [text block]",
  "ssmt-mpers:DisclosureOfEntitysReportableSegmentsExplanatory": "Disclosure of entity's operating segments [text block]",
  "ssmt-mpers:DisclosureOfExplanationOfTransitionToMPERSExplanatory": "Disclosure of explanation of transition to the MPERS [text block]",
  "ssmt-mpers:DisclosureOfFeeAndCommissionIncomeExpenseExplanatory": "Disclosure of fee and commission income (expense) [text block]",
  "ssmt-mpers:DisclosureOfFinanceIncomeExplanatory": "Disclosure of finance income [text block]",
  "ssmt-mpers:DisclosureOfFinancialInstrumentsAtFairValueThroughProfitOrLossExplanatory": "Disclosure of financial instruments at fair value through profit or loss [text block]",
  "ssmt-mpers:DisclosureOfFinancialInstrumentsMeasuredAtAmortisedCostExplanatory": "Disclosure of financial instrument measured at amortised cost [text block]",
  "ssmt-mpers:DisclosureOfForeignCurrencyTranslationReserveExplanatory": "Disclosure of foreign currency translation reserve [text block]",
  "ssmt-mpers:DisclosureOfGoingConcernExplanatory": "Disclosure of going concern [text block]",
  "ssmt-mpers:DisclosureOfGrantsAndContributionsExplanatory": "Disclosure of grants and contributions [text block]",
  "ssmt-mpers:DisclosureOfHedgingActivityExplanatory": "Disclosure of hedging activities [text block]",
  "ssmt-mpers:DisclosureOfImpairmentOfAssetsExplanatory": "Disclosure of impairment of assets [text block]",
  "ssmt-mpers:DisclosureOfIntangibleAssetsAndGoodwillExplanatory": "Disclosure of intangible assets [text block]",
  "ssmt-mpers:DisclosureOfInterestExpenseExplanatory": "Disclosure of interest expense [text block]",
  "ssmt-mpers:DisclosureOfInterestInAssociatesJointVenturesOrJointlyControlledOperationExplanatory": "Disclosure of interest in associates, joint ventures or jointly controlled operation [text block]",
  "ssmt-mpers:DisclosureOfInterestIncomeExplanatory": "Disclosure of interest income [text block]",
  "ssmt-mpers:DisclosureOfInvestmentInJointlyControlledExplanatory": "Disclosure of investment in jointly controlled entities [text block]",
  "ssmt-mpers:DisclosureOfInvestmentInSubsidiaryCompaniesExplanatory": "Disclosure of investment in subsidiaries [text block]",
  "ssmt-mpers:DisclosureOfLiquidityRiskExplanatory": "Disclosure of liquidity risk [text block]",
  "ssmt-mpers:DisclosureOfLoansAndAdvancesToBanksExplanatory": "Disclosure of loans and advances to banks [text block]",
  "ssmt-mpers:DisclosureOfMarketRiskExplanatory": "Disclosure of market risk [text block]",
  "ssmt-mpers:DisclosureOfNonAdjustingEventsAfterEndOfReportingPeriodExplanatory": "Disclosure of non-adjusting events after the end of reporting period [text block]",
  "ssmt-mpers:DisclosureOfNoncontrollingInterestsExplanatory": "Disclosure of non-controlling interests [text block]",
  "ssmt-mpers:DisclosureOfNoncurrentAssetsHeldForSaleAndDiscontinuedOperationsExplanatory": "Disclosure of non-current assets or disposal groups classified as held for sale [text block]",
  "ssmt-mpers:DisclosureOfOtherComprehensiveIncomeExplanatory": "Disclosure of other comprehensive income [text block]",
  "ssmt-mpers:DisclosureOfOtherCurrentAssetsExplanatory": "Disclosure of other current assets [text block]",
  "ssmt-mpers:DisclosureOfOtherCurrentLiabilitiesExplanatory": "Disclosure of other current liabilities [text block]",
  "ssmt-mpers:DisclosureOfOtherLongTermEmploymentBenefitsExplanatory": "Disclosure of other long-term employment benefits [text block]",
  "ssmt-mpers:DisclosureOfOtherNoncurrentAssetsExplanatory": "Disclosure of other non-current assets [text block]",
  "ssmt-mpers:DisclosureOfOtherNoncurrentLiabilitiesExplanatory": "Disclosure of other non-current liabilities [text block]",
  "ssmt-mpers:DisclosureOfOtherOperatingExpenseExplanatory": "Disclosure of other operating expense [text block]",
  "ssmt-mpers:DisclosureOfOtherReservesExplanatory": "Disclosure of other reserves [text block]",
  "ssmt-mpers:DisclosureOfPerpetualSukukExplanatory": "Disclosure of perpetual sukuk [text block]",
  "ssmt-mpers:DisclosureOfPostEmploymentBenefitObligationsExplanatory": "Disclosure of post employment benefit obligation [text block]",
  "ssmt-mpers:DisclosureOfProvisionsExplanatory": "Disclosure of provisions [text block]",
  "ssmt-mpers:DisclosureOfRedeemablePreferenceSharesExplanatory": "Disclosure of redeemable preference shares [text block]",
  "ssmt-mpers:DisclosureOfServiceConcessionArrangementsExplanatory": "Disclosure of service concession arrangements [text block]",
  "ssmt-mpers:DisclosureOfSubsequentEventsExplanatory": "Disclosure of subsequent event [text block]",
  "ssmt-mpers:ExplanationOfReasonsForReclassificationOfPreviousFinancialStatementsFiguresExplanatory": "Explanation of reasons for the reclassification of previous financial statements figures [textblock]",
  "ssmt-mpers:ExplanationOfReasonsForRestatementOfPreviousFinancialStatementsFiguresExplanatory": "Explanation of reasons for the restatement of previous financial statements figures [textblock]",
  "ssmt-mpers:ExplanationOfReasonsForUsingLongerOrShorterReportingPeriodExplanatory": "Explanation of reasons for using longer or shorter reporting period [textblock]",
};
